const int flash_events_ErrorEvent_private_setID = 2;
const int flash_events_ErrorEvent_errorID_get = 3;
const int flash_events_ErrorEvent_clone = 4;
const int flash_events_ErrorEvent_toString = 5;
const int abcclass_flash_events_ErrorEvent = 0;
extern const int ErrorEvent_abc_length;
extern const int ErrorEvent_abc_method_count;
extern const int ErrorEvent_abc_class_count;
extern const int ErrorEvent_abc_script_count;
extern const unsigned char ErrorEvent_abc_data[];
