const int flash_events_KeyboardEvent_charCode_get = 2;
const int flash_events_KeyboardEvent_charCode_set = 3;
const int flash_events_KeyboardEvent_keyCode_get = 4;
const int flash_events_KeyboardEvent_keyCode_set = 5;
const int flash_events_KeyboardEvent_keyLocation_get = 6;
const int flash_events_KeyboardEvent_keyLocation_set = 7;
const int flash_events_KeyboardEvent_ctrlKey_get = 8;
const int flash_events_KeyboardEvent_ctrlKey_set = 9;
const int flash_events_KeyboardEvent_altKey_get = 10;
const int flash_events_KeyboardEvent_altKey_set = 11;
const int flash_events_KeyboardEvent_shiftKey_get = 12;
const int flash_events_KeyboardEvent_shiftKey_set = 13;
const int flash_events_KeyboardEvent_clone = 14;
const int flash_events_KeyboardEvent_toString = 15;
const int flash_events_KeyboardEvent_updateAfterEvent = 16;
const int abcclass_flash_events_KeyboardEvent = 0;
extern const int KeyboardEvent_abc_length;
extern const int KeyboardEvent_abc_method_count;
extern const int KeyboardEvent_abc_class_count;
extern const int KeyboardEvent_abc_script_count;
extern const unsigned char KeyboardEvent_abc_data[];
