const int flash_events_TouchEvent_touchPointID_get = 2;
const int flash_events_TouchEvent_touchPointID_set = 3;
const int flash_events_TouchEvent_isPrimaryTouchPoint_get = 4;
const int flash_events_TouchEvent_isPrimaryTouchPoint_set = 5;
const int flash_events_TouchEvent_localX_get = 6;
const int flash_events_TouchEvent_localX_set = 7;
const int flash_events_TouchEvent_localY_get = 8;
const int flash_events_TouchEvent_localY_set = 9;
const int flash_events_TouchEvent_sizeX_get = 10;
const int flash_events_TouchEvent_sizeX_set = 11;
const int flash_events_TouchEvent_sizeY_get = 12;
const int flash_events_TouchEvent_sizeY_set = 13;
const int flash_events_TouchEvent_pressure_get = 14;
const int flash_events_TouchEvent_pressure_set = 15;
const int flash_events_TouchEvent_relatedObject_get = 16;
const int flash_events_TouchEvent_relatedObject_set = 17;
const int flash_events_TouchEvent_ctrlKey_get = 18;
const int flash_events_TouchEvent_ctrlKey_set = 19;
const int flash_events_TouchEvent_altKey_get = 20;
const int flash_events_TouchEvent_altKey_set = 21;
const int flash_events_TouchEvent_shiftKey_get = 22;
const int flash_events_TouchEvent_shiftKey_set = 23;
const int flash_events_TouchEvent_stageX_get = 24;
const int flash_events_TouchEvent_stageY_get = 25;
const int flash_events_TouchEvent_isRelatedObjectInaccessible_get = 26;
const int flash_events_TouchEvent_isRelatedObjectInaccessible_set = 27;
const int flash_events_TouchEvent_clone = 28;
const int flash_events_TouchEvent_toString = 29;
const int flash_events_TouchEvent_updateAfterEvent = 30;
const int abcclass_flash_events_TouchEvent = 0;
extern const int TouchEvent_abc_length;
extern const int TouchEvent_abc_method_count;
extern const int TouchEvent_abc_class_count;
extern const int TouchEvent_abc_script_count;
extern const unsigned char TouchEvent_abc_data[];
