const int flash_ui_ContextMenuClipboardItems_ContextMenuClipboardItems = 1;
const int flash_ui_ContextMenuClipboardItems_cut_get = 2;
const int flash_ui_ContextMenuClipboardItems_cut_set = 3;
const int flash_ui_ContextMenuClipboardItems_copy_get = 4;
const int flash_ui_ContextMenuClipboardItems_copy_set = 5;
const int flash_ui_ContextMenuClipboardItems_paste_get = 6;
const int flash_ui_ContextMenuClipboardItems_paste_set = 7;
const int flash_ui_ContextMenuClipboardItems_clear_get = 8;
const int flash_ui_ContextMenuClipboardItems_clear_set = 9;
const int flash_ui_ContextMenuClipboardItems_selectAll_get = 10;
const int flash_ui_ContextMenuClipboardItems_selectAll_set = 11;
const int flash_ui_ContextMenuClipboardItems_clone = 12;
const int abcclass_flash_ui_ContextMenuClipboardItems = 0;
extern const int ContextMenuClipboardItems_abc_length;
extern const int ContextMenuClipboardItems_abc_method_count;
extern const int ContextMenuClipboardItems_abc_class_count;
extern const int ContextMenuClipboardItems_abc_script_count;
extern const unsigned char ContextMenuClipboardItems_abc_data[];
