const int flash_net_SharedObject_deleteAll = 1;
const int flash_net_SharedObject_getDiskUsage = 2;
const int flash_net_SharedObject_getLocal = 3;
const int flash_net_SharedObject_getRemote = 4;
const int flash_net_SharedObject_defaultObjectEncoding_get = 5;
const int flash_net_SharedObject_defaultObjectEncoding_set = 6;
const int flash_net_SharedObject_SharedObject = 7;
const int flash_net_SharedObject_data_get = 8;
const int flash_net_SharedObject_connect = 9;
const int flash_net_SharedObject_close = 10;
const int flash_net_SharedObject_flush = 11;
const int flash_net_SharedObject_size_get = 12;
const int flash_net_SharedObject_fps_set = 13;
const int flash_net_SharedObject_send = 14;
const int flash_net_SharedObject_clear = 15;
const int flash_net_SharedObject_objectEncoding_get = 16;
const int flash_net_SharedObject_objectEncoding_set = 17;
const int flash_net_SharedObject_client_get = 18;
const int flash_net_SharedObject_client_set = 19;
const int flash_net_SharedObject_setDirty = 20;
const int flash_net_SharedObject_setProperty = 21;
const int abcclass_flash_net_SharedObject = 0;
extern const int SharedObject_abc_length;
extern const int SharedObject_abc_method_count;
extern const int SharedObject_abc_class_count;
extern const int SharedObject_abc_script_count;
extern const unsigned char SharedObject_abc_data[];
