const int flash_system_AuthorizedFeatures_createApplicationInstaller = 2;
const int flash_system_AuthorizedFeatures_enableDiskCache = 3;
const int flash_system_AuthorizedFeatures_flash_system_isFeatureEnabled = 4;
const int flash_system_AuthorizedFeatures_flash_system_isNegativeToken = 5;
const int abcclass_flash_system_AuthorizedFeatures = 0;
extern const int AuthorizedFeatures_abc_length;
extern const int AuthorizedFeatures_abc_method_count;
extern const int AuthorizedFeatures_abc_class_count;
extern const int AuthorizedFeatures_abc_script_count;
extern const unsigned char AuthorizedFeatures_abc_data[];
