const int flash_system_System_ime_get = 1;
const int flash_system_System_totalMemoryNumber_get = 2;
const int flash_system_System_freeMemory_get = 3;
const int flash_system_System_privateMemory_get = 4;
const int flash_system_System_useCodePage_get = 5;
const int flash_system_System_useCodePage_set = 6;
const int flash_system_System_vmVersion_get = 7;
const int flash_system_System_setClipboard = 8;
const int flash_system_System_pause = 10;
const int flash_system_System_resume = 11;
const int flash_system_System_exit = 12;
const int flash_system_System_gc = 13;
const int flash_system_System_pauseForGCIfCollectionImminent = 14;
const int flash_system_System_disposeXML = 15;
const int abcclass_flash_system_System = 0;
extern const int System_abc_length;
extern const int System_abc_method_count;
extern const int System_abc_class_count;
extern const int System_abc_script_count;
extern const unsigned char System_abc_data[];
