const int flash_text_engine_ElementFormat_alignmentBaseline_get = 2;
const int flash_text_engine_ElementFormat_alignmentBaseline_set = 3;
const int flash_text_engine_ElementFormat_alpha_get = 4;
const int flash_text_engine_ElementFormat_alpha_set = 5;
const int flash_text_engine_ElementFormat_baselineShift_get = 6;
const int flash_text_engine_ElementFormat_baselineShift_set = 7;
const int flash_text_engine_ElementFormat_breakOpportunity_get = 8;
const int flash_text_engine_ElementFormat_breakOpportunity_set = 9;
const int flash_text_engine_ElementFormat_color_get = 10;
const int flash_text_engine_ElementFormat_color_set = 11;
const int flash_text_engine_ElementFormat_dominantBaseline_get = 12;
const int flash_text_engine_ElementFormat_dominantBaseline_set = 13;
const int flash_text_engine_ElementFormat_fontDescription_get = 14;
const int flash_text_engine_ElementFormat_fontDescription_set = 15;
const int flash_text_engine_ElementFormat_digitCase_get = 16;
const int flash_text_engine_ElementFormat_digitCase_set = 17;
const int flash_text_engine_ElementFormat_digitWidth_get = 18;
const int flash_text_engine_ElementFormat_digitWidth_set = 19;
const int flash_text_engine_ElementFormat_ligatureLevel_get = 20;
const int flash_text_engine_ElementFormat_ligatureLevel_set = 21;
const int flash_text_engine_ElementFormat_fontSize_get = 22;
const int flash_text_engine_ElementFormat_fontSize_set = 23;
const int flash_text_engine_ElementFormat_kerning_get = 24;
const int flash_text_engine_ElementFormat_kerning_set = 25;
const int flash_text_engine_ElementFormat_locale_get = 26;
const int flash_text_engine_ElementFormat_locale_set = 27;
const int flash_text_engine_ElementFormat_textRotation_get = 28;
const int flash_text_engine_ElementFormat_textRotation_set = 29;
const int flash_text_engine_ElementFormat_trackingRight_get = 30;
const int flash_text_engine_ElementFormat_trackingRight_set = 31;
const int flash_text_engine_ElementFormat_trackingLeft_get = 32;
const int flash_text_engine_ElementFormat_trackingLeft_set = 33;
const int flash_text_engine_ElementFormat_typographicCase_get = 34;
const int flash_text_engine_ElementFormat_typographicCase_set = 35;
const int flash_text_engine_ElementFormat_locked_get = 36;
const int flash_text_engine_ElementFormat_locked_set = 37;
const int flash_text_engine_ElementFormat_getFontMetrics = 38;
const int abcclass_flash_text_engine_ElementFormat = 0;
extern const int ElementFormat_abc_length;
extern const int ElementFormat_abc_method_count;
extern const int ElementFormat_abc_class_count;
extern const int ElementFormat_abc_script_count;
extern const unsigned char ElementFormat_abc_data[];
