const int flash_text_engine_FontDescription_isFontCompatible = 1;
const int flash_text_engine_FontDescription_isDeviceFontCompatible = 2;
const int flash_text_engine_FontDescription_renderingMode_get = 4;
const int flash_text_engine_FontDescription_renderingMode_set = 5;
const int flash_text_engine_FontDescription_fontLookup_get = 6;
const int flash_text_engine_FontDescription_fontLookup_set = 7;
const int flash_text_engine_FontDescription_fontName_get = 8;
const int flash_text_engine_FontDescription_fontName_set = 9;
const int flash_text_engine_FontDescription_fontPosture_get = 10;
const int flash_text_engine_FontDescription_fontPosture_set = 11;
const int flash_text_engine_FontDescription_fontWeight_get = 12;
const int flash_text_engine_FontDescription_fontWeight_set = 13;
const int flash_text_engine_FontDescription_cffHinting_get = 14;
const int flash_text_engine_FontDescription_cffHinting_set = 15;
const int flash_text_engine_FontDescription_locked_get = 16;
const int flash_text_engine_FontDescription_locked_set = 17;
const int abcclass_flash_text_engine_FontDescription = 0;
extern const int FontDescription_abc_length;
extern const int FontDescription_abc_method_count;
extern const int FontDescription_abc_class_count;
extern const int FontDescription_abc_script_count;
extern const unsigned char FontDescription_abc_data[];
