const int flash_text_engine_GraphicElement_graphic_get = 2;
const int flash_text_engine_GraphicElement_graphic_set = 3;
const int flash_text_engine_GraphicElement_elementHeight_get = 4;
const int flash_text_engine_GraphicElement_elementHeight_set = 5;
const int flash_text_engine_GraphicElement_elementWidth_get = 6;
const int flash_text_engine_GraphicElement_elementWidth_set = 7;
const int abcclass_flash_text_engine_GraphicElement = 0;
extern const int GraphicElement_abc_length;
extern const int GraphicElement_abc_method_count;
extern const int GraphicElement_abc_class_count;
extern const int GraphicElement_abc_script_count;
extern const unsigned char GraphicElement_abc_data[];
