const int flash_text_engine_GroupElement_elementCount_get = 2;
const int flash_text_engine_GroupElement_getElementAt = 3;
const int flash_text_engine_GroupElement_setElements = 4;
const int flash_text_engine_GroupElement_groupElements = 5;
const int flash_text_engine_GroupElement_ungroupElements = 6;
const int flash_text_engine_GroupElement_mergeTextElements = 7;
const int flash_text_engine_GroupElement_splitTextElement = 8;
const int flash_text_engine_GroupElement_replaceElements = 9;
const int flash_text_engine_GroupElement_getElementAtCharIndex = 10;
const int abcclass_flash_text_engine_GroupElement = 0;
extern const int GroupElement_abc_length;
extern const int GroupElement_abc_method_count;
extern const int GroupElement_abc_class_count;
extern const int GroupElement_abc_script_count;
extern const unsigned char GroupElement_abc_data[];
