const int flash_text_engine_TabStop_alignment_get = 2;
const int flash_text_engine_TabStop_alignment_set = 3;
const int flash_text_engine_TabStop_position_get = 4;
const int flash_text_engine_TabStop_position_set = 5;
const int flash_text_engine_TabStop_decimalAlignmentToken_get = 6;
const int flash_text_engine_TabStop_decimalAlignmentToken_set = 7;
const int abcclass_flash_text_engine_TabStop = 0;
extern const int TabStop_abc_length;
extern const int TabStop_abc_method_count;
extern const int TabStop_abc_class_count;
extern const int TabStop_abc_script_count;
extern const unsigned char TabStop_abc_data[];
