const int flash_text_engine_TextLine_textBlock_get = 7;
const int flash_text_engine_TextLine_hasGraphicElement_get = 8;
const int flash_text_engine_TextLine_hasTabs_get = 9;
const int flash_text_engine_TextLine_nextLine_get = 10;
const int flash_text_engine_TextLine_previousLine_get = 11;
const int flash_text_engine_TextLine_ascent_get = 12;
const int flash_text_engine_TextLine_descent_get = 13;
const int flash_text_engine_TextLine_textHeight_get = 14;
const int flash_text_engine_TextLine_textWidth_get = 15;
const int flash_text_engine_TextLine_totalAscent_get = 16;
const int flash_text_engine_TextLine_totalDescent_get = 17;
const int flash_text_engine_TextLine_totalHeight_get = 18;
const int flash_text_engine_TextLine_textBlockBeginIndex_get = 19;
const int flash_text_engine_TextLine_rawTextLength_get = 20;
const int flash_text_engine_TextLine_specifiedWidth_get = 21;
const int flash_text_engine_TextLine_unjustifiedTextWidth_get = 22;
const int flash_text_engine_TextLine_validity_get = 23;
const int flash_text_engine_TextLine_validity_set = 24;
const int flash_text_engine_TextLine_atomCount_get = 25;
const int flash_text_engine_TextLine_mirrorRegions_get = 26;
const int flash_text_engine_TextLine_getAtomIndexAtPoint = 29;
const int flash_text_engine_TextLine_getAtomIndexAtCharIndex = 30;
const int flash_text_engine_TextLine_getAtomBounds = 31;
const int flash_text_engine_TextLine_getAtomBidiLevel = 32;
const int flash_text_engine_TextLine_getAtomTextRotation = 33;
const int flash_text_engine_TextLine_getAtomTextBlockBeginIndex = 34;
const int flash_text_engine_TextLine_getAtomTextBlockEndIndex = 35;
const int flash_text_engine_TextLine_getAtomCenter = 36;
const int flash_text_engine_TextLine_getAtomWordBoundaryOnLeft = 37;
const int flash_text_engine_TextLine_getAtomGraphic = 38;
const int flash_text_engine_TextLine_getBaselinePosition = 39;
const int flash_text_engine_TextLine_dump = 40;
const int abcclass_flash_text_engine_TextLine = 0;
extern const int TextLine_abc_length;
extern const int TextLine_abc_method_count;
extern const int TextLine_abc_class_count;
extern const int TextLine_abc_script_count;
extern const unsigned char TextLine_abc_data[];
