const int flash_text_engine_TextJustifier_locale_get = 3;
const int flash_text_engine_TextJustifier_lineJustification_get = 4;
const int flash_text_engine_TextJustifier_lineJustification_set = 5;
const int flash_text_engine_TextJustifier_private_setLocale = 7;
const int abcclass_flash_text_engine_TextJustifier = 0;
extern const int TextJustifier_abc_length;
extern const int TextJustifier_abc_method_count;
extern const int TextJustifier_abc_class_count;
extern const int TextJustifier_abc_script_count;
extern const unsigned char TextJustifier_abc_data[];
