const int flash_text_engine_TextBlock_applyNonLinearFontScaling_get = 2;
const int flash_text_engine_TextBlock_applyNonLinearFontScaling_set = 3;
const int flash_text_engine_TextBlock_baselineFontDescription_get = 4;
const int flash_text_engine_TextBlock_baselineFontDescription_set = 5;
const int flash_text_engine_TextBlock_baselineFontSize_get = 6;
const int flash_text_engine_TextBlock_baselineFontSize_set = 7;
const int flash_text_engine_TextBlock_baselineZero_get = 8;
const int flash_text_engine_TextBlock_baselineZero_set = 9;
const int flash_text_engine_TextBlock_content_get = 10;
const int flash_text_engine_TextBlock_content_set = 11;
const int flash_text_engine_TextBlock_bidiLevel_get = 12;
const int flash_text_engine_TextBlock_bidiLevel_set = 13;
const int flash_text_engine_TextBlock_firstInvalidLine_get = 14;
const int flash_text_engine_TextBlock_firstLine_get = 15;
const int flash_text_engine_TextBlock_lastLine_get = 16;
const int flash_text_engine_TextBlock_textLineCreationResult_get = 19;
const int flash_text_engine_TextBlock_lineRotation_get = 20;
const int flash_text_engine_TextBlock_lineRotation_set = 21;
const int flash_text_engine_TextBlock_findNextAtomBoundary = 24;
const int flash_text_engine_TextBlock_findPreviousAtomBoundary = 25;
const int flash_text_engine_TextBlock_findNextWordBoundary = 26;
const int flash_text_engine_TextBlock_findPreviousWordBoundary = 27;
const int flash_text_engine_TextBlock_getTextLineAtCharIndex = 28;
const int flash_text_engine_TextBlock_releaseLineCreationData = 31;
const int flash_text_engine_TextBlock_releaseLines = 32;
const int flash_text_engine_TextBlock_dump = 33;
const int flash_text_engine_TextBlock_private_DoCreateTextLine = 34;
const int flash_text_engine_TextBlock_private_getTabStops = 35;
const int flash_text_engine_TextBlock_private_setTabStops = 36;
const int flash_text_engine_TextBlock_private_getTextJustifier = 37;
const int flash_text_engine_TextBlock_private_setTextJustifier = 38;
const int abcclass_flash_text_engine_TextBlock = 0;
extern const int TextBlock_abc_length;
extern const int TextBlock_abc_method_count;
extern const int TextBlock_abc_class_count;
extern const int TextBlock_abc_script_count;
extern const unsigned char TextBlock_abc_data[];
