const int flash_text_engine_TextLineMirrorRegion_textLine_get = 2;
const int flash_text_engine_TextLineMirrorRegion_nextRegion_get = 3;
const int flash_text_engine_TextLineMirrorRegion_previousRegion_get = 4;
const int flash_text_engine_TextLineMirrorRegion_mirror_get = 5;
const int flash_text_engine_TextLineMirrorRegion_element_get = 6;
const int flash_text_engine_TextLineMirrorRegion_bounds_get = 7;
const int abcclass_flash_text_engine_TextLineMirrorRegion = 0;
extern const int TextLineMirrorRegion_abc_length;
extern const int TextLineMirrorRegion_abc_method_count;
extern const int TextLineMirrorRegion_abc_class_count;
extern const int TextLineMirrorRegion_abc_script_count;
extern const unsigned char TextLineMirrorRegion_abc_data[];
