const int flash_profiler_Telemetry_spanMarker_get = 1;
const int flash_profiler_Telemetry_connected_get = 2;
const int flash_profiler_Telemetry_sendMetric = 3;
const int flash_profiler_Telemetry_sendSpanMetric = 4;
const int flash_profiler_Telemetry_registerCommandHandler = 5;
const int flash_profiler_Telemetry_unregisterCommandHandler = 6;
const int abcclass_flash_profiler_Telemetry = 0;
extern const int Telemetry_abc_length;
extern const int Telemetry_abc_method_count;
extern const int Telemetry_abc_class_count;
extern const int Telemetry_abc_script_count;
extern const unsigned char Telemetry_abc_data[];
