const int flash_text_StyleSheet_StyleSheet = 1;
const int flash_text_StyleSheet_styleNames_get = 2;
const int flash_text_StyleSheet_getStyle = 3;
const int flash_text_StyleSheet_setStyle = 4;
const int flash_text_StyleSheet_clear = 5;
const int flash_text_StyleSheet_transform = 6;
const int flash_text_StyleSheet_parseCSS = 7;
const int abcclass_flash_text_StyleSheet = 0;
extern const int StyleSheet_abc_length;
extern const int StyleSheet_abc_method_count;
extern const int StyleSheet_abc_class_count;
extern const int StyleSheet_abc_script_count;
extern const unsigned char StyleSheet_abc_data[];
