const int flash_text_TextFormat_TextFormat = 1;
const int flash_text_TextFormat_align_get = 2;
const int flash_text_TextFormat_align_set = 3;
const int flash_text_TextFormat_blockIndent_get = 4;
const int flash_text_TextFormat_blockIndent_set = 5;
const int flash_text_TextFormat_bold_get = 6;
const int flash_text_TextFormat_bold_set = 7;
const int flash_text_TextFormat_bullet_get = 8;
const int flash_text_TextFormat_bullet_set = 9;
const int flash_text_TextFormat_color_get = 10;
const int flash_text_TextFormat_color_set = 11;
const int flash_text_TextFormat_display_get = 12;
const int flash_text_TextFormat_display_set = 13;
const int flash_text_TextFormat_font_get = 14;
const int flash_text_TextFormat_font_set = 15;
const int flash_text_TextFormat_indent_get = 16;
const int flash_text_TextFormat_indent_set = 17;
const int flash_text_TextFormat_italic_get = 18;
const int flash_text_TextFormat_italic_set = 19;
const int flash_text_TextFormat_kerning_get = 20;
const int flash_text_TextFormat_kerning_set = 21;
const int flash_text_TextFormat_leading_get = 22;
const int flash_text_TextFormat_leading_set = 23;
const int flash_text_TextFormat_leftMargin_get = 24;
const int flash_text_TextFormat_leftMargin_set = 25;
const int flash_text_TextFormat_letterSpacing_get = 26;
const int flash_text_TextFormat_letterSpacing_set = 27;
const int flash_text_TextFormat_rightMargin_get = 28;
const int flash_text_TextFormat_rightMargin_set = 29;
const int flash_text_TextFormat_size_get = 30;
const int flash_text_TextFormat_size_set = 31;
const int flash_text_TextFormat_tabStops_get = 32;
const int flash_text_TextFormat_tabStops_set = 33;
const int flash_text_TextFormat_target_get = 34;
const int flash_text_TextFormat_target_set = 35;
const int flash_text_TextFormat_underline_get = 36;
const int flash_text_TextFormat_underline_set = 37;
const int flash_text_TextFormat_url_get = 38;
const int flash_text_TextFormat_url_set = 39;
const int abcclass_flash_text_TextFormat = 0;
extern const int TextFormat_abc_length;
extern const int TextFormat_abc_method_count;
extern const int TextFormat_abc_class_count;
extern const int TextFormat_abc_script_count;
extern const unsigned char TextFormat_abc_data[];
