const int flash_text_TextRun_TextRun = 1;
const int flash_text_TextRun_beginIndex_get = 2;
const int flash_text_TextRun_beginIndex_set = 3;
const int flash_text_TextRun_endIndex_get = 4;
const int flash_text_TextRun_endIndex_set = 5;
const int flash_text_TextRun_textFormat_get = 6;
const int flash_text_TextRun_textFormat_set = 7;
const int abcclass_flash_text_TextRun = 0;
extern const int TextRun_abc_length;
extern const int TextRun_abc_method_count;
extern const int TextRun_abc_class_count;
extern const int TextRun_abc_script_count;
extern const unsigned char TextRun_abc_data[];
