#!/bin/sh
termux-setup-storage
pkg install clang wget -y
if [ ! -f empires-v260 ]; then
wget "https://github.com/Questandachievement7Developer/RaiseTheEmpiresPort_Native/releases/download/Build_260/empires-v260" -O empires-v260
else
echo "empires-server has been downloaded"
fi
