const int flash_utils_Timer_Timer = 1;
const int flash_utils_Timer_running_get = 2;
const int flash_utils_Timer_delay_get = 3;
const int flash_utils_Timer_delay_set = 4;
const int flash_utils_Timer_repeatCount_get = 5;
const int flash_utils_Timer_repeatCount_set = 6;
const int flash_utils_Timer_currentCount_get = 7;
const int flash_utils_Timer_reset = 8;
const int flash_utils_Timer_stop = 9;
const int flash_utils_Timer_start = 10;
const int abcclass_flash_utils_Timer = 0;
extern const int Timer_abc_length;
extern const int Timer_abc_method_count;
extern const int Timer_abc_class_count;
extern const int Timer_abc_script_count;
extern const unsigned char Timer_abc_data[];
