const int flash_events_EventDispatcher_EventDispatcher = 1;
const int flash_events_EventDispatcher_toString = 2;
const int flash_events_EventDispatcher_addEventListener = 3;
const int flash_events_EventDispatcher_removeEventListener = 4;
const int flash_events_EventDispatcher_hasEventListener = 5;
const int flash_events_EventDispatcher_willTrigger = 6;
const int flash_events_EventDispatcher_dispatchEvent = 7;
const int abcclass_flash_events_EventDispatcher = 0;
extern const int EventDispatcher_abc_length;
extern const int EventDispatcher_abc_method_count;
extern const int EventDispatcher_abc_class_count;
extern const int EventDispatcher_abc_script_count;
extern const unsigned char EventDispatcher_abc_data[];
