const int flash_events_Event_Event = 1;
const int flash_events_Event_type_get = 2;
const int flash_events_Event_bubbles_get = 3;
const int flash_events_Event_cancelable_get = 4;
const int flash_events_Event_target_get = 5;
const int flash_events_Event_currentTarget_get = 6;
const int flash_events_Event_eventPhase_get = 7;
const int flash_events_Event_formatToString = 8;
const int flash_events_Event_clone = 9;
const int flash_events_Event_toString = 10;
const int flash_events_Event_stopPropagation = 11;
const int flash_events_Event_stopImmediatePropagation = 12;
const int flash_events_Event_preventDefault = 13;
const int flash_events_Event_isDefaultPrevented = 14;
const int abcclass_flash_events_Event = 0;
extern const int Event_abc_length;
extern const int Event_abc_method_count;
extern const int Event_abc_class_count;
extern const int Event_abc_script_count;
extern const unsigned char Event_abc_data[];
