const int flash_events_GestureEvent_localX_get = 2;
const int flash_events_GestureEvent_localX_set = 3;
const int flash_events_GestureEvent_localY_get = 4;
const int flash_events_GestureEvent_localY_set = 5;
const int flash_events_GestureEvent_phase_get = 6;
const int flash_events_GestureEvent_phase_set = 7;
const int flash_events_GestureEvent_ctrlKey_get = 8;
const int flash_events_GestureEvent_ctrlKey_set = 9;
const int flash_events_GestureEvent_altKey_get = 10;
const int flash_events_GestureEvent_altKey_set = 11;
const int flash_events_GestureEvent_shiftKey_get = 12;
const int flash_events_GestureEvent_shiftKey_set = 13;
const int flash_events_GestureEvent_stageX_get = 14;
const int flash_events_GestureEvent_stageY_get = 15;
const int flash_events_GestureEvent_clone = 16;
const int flash_events_GestureEvent_toString = 17;
const int flash_events_GestureEvent_updateAfterEvent = 18;
const int flash_events_GestureEvent_private_NativeCtor = 19;
const int abcclass_flash_events_GestureEvent = 0;
extern const int GestureEvent_abc_length;
extern const int GestureEvent_abc_method_count;
extern const int GestureEvent_abc_class_count;
extern const int GestureEvent_abc_script_count;
extern const unsigned char GestureEvent_abc_data[];
