const int flash_events_HTTPStatusEvent_private__setStatus = 2;
const int flash_events_HTTPStatusEvent_status_get = 3;
const int flash_events_HTTPStatusEvent_clone = 4;
const int flash_events_HTTPStatusEvent_toString = 5;
const int abcclass_flash_events_HTTPStatusEvent = 0;
extern const int HTTPStatusEvent_abc_length;
extern const int HTTPStatusEvent_abc_method_count;
extern const int HTTPStatusEvent_abc_class_count;
extern const int HTTPStatusEvent_abc_script_count;
extern const unsigned char HTTPStatusEvent_abc_data[];
