const int flash_events_MouseEvent_localX_get = 2;
const int flash_events_MouseEvent_localX_set = 3;
const int flash_events_MouseEvent_localY_get = 4;
const int flash_events_MouseEvent_localY_set = 5;
const int flash_events_MouseEvent_stageX_get = 6;
const int flash_events_MouseEvent_stageY_get = 7;
const int flash_events_MouseEvent_movementX_get = 8;
const int flash_events_MouseEvent_movementX_set = 9;
const int flash_events_MouseEvent_movementY_get = 10;
const int flash_events_MouseEvent_movementY_set = 11;
const int flash_events_MouseEvent_delta_get = 12;
const int flash_events_MouseEvent_delta_set = 13;
const int flash_events_MouseEvent_ctrlKey_get = 14;
const int flash_events_MouseEvent_ctrlKey_set = 15;
const int flash_events_MouseEvent_altKey_get = 16;
const int flash_events_MouseEvent_altKey_set = 17;
const int flash_events_MouseEvent_shiftKey_get = 18;
const int flash_events_MouseEvent_shiftKey_set = 19;
const int flash_events_MouseEvent_buttonDown_get = 20;
const int flash_events_MouseEvent_buttonDown_set = 21;
const int flash_events_MouseEvent_relatedObject_get = 22;
const int flash_events_MouseEvent_relatedObject_set = 23;
const int flash_events_MouseEvent_isRelatedObjectInaccessible_get = 24;
const int flash_events_MouseEvent_isRelatedObjectInaccessible_set = 25;
const int flash_events_MouseEvent_clone = 26;
const int flash_events_MouseEvent_toString = 27;
const int flash_events_MouseEvent_updateAfterEvent = 28;
const int abcclass_flash_events_MouseEvent = 0;
extern const int MouseEvent_abc_length;
extern const int MouseEvent_abc_method_count;
extern const int MouseEvent_abc_class_count;
extern const int MouseEvent_abc_script_count;
extern const unsigned char MouseEvent_abc_data[];
