const int flash_events_NetStatusEvent_info_get = 2;
const int flash_events_NetStatusEvent_info_set = 3;
const int flash_events_NetStatusEvent_clone = 4;
const int flash_events_NetStatusEvent_toString = 5;
const int abcclass_flash_events_NetStatusEvent = 0;
extern const int NetStatusEvent_abc_length;
extern const int NetStatusEvent_abc_method_count;
extern const int NetStatusEvent_abc_class_count;
extern const int NetStatusEvent_abc_script_count;
extern const unsigned char NetStatusEvent_abc_data[];
