const int flash_events_ProgressEvent_bytesLoaded_get = 2;
const int flash_events_ProgressEvent_bytesLoaded_set = 3;
const int flash_events_ProgressEvent_bytesTotal_get = 4;
const int flash_events_ProgressEvent_bytesTotal_set = 5;
const int flash_events_ProgressEvent_clone = 6;
const int flash_events_ProgressEvent_toString = 7;
const int abcclass_flash_events_ProgressEvent = 0;
extern const int ProgressEvent_abc_length;
extern const int ProgressEvent_abc_method_count;
extern const int ProgressEvent_abc_class_count;
extern const int ProgressEvent_abc_script_count;
extern const unsigned char ProgressEvent_abc_data[];
