const int flash_events_StatusEvent_code_get = 2;
const int flash_events_StatusEvent_code_set = 3;
const int flash_events_StatusEvent_level_get = 4;
const int flash_events_StatusEvent_level_set = 5;
const int flash_events_StatusEvent_clone = 6;
const int flash_events_StatusEvent_toString = 7;
const int abcclass_flash_events_StatusEvent = 0;
extern const int StatusEvent_abc_length;
extern const int StatusEvent_abc_method_count;
extern const int StatusEvent_abc_class_count;
extern const int StatusEvent_abc_script_count;
extern const unsigned char StatusEvent_abc_data[];
