const int flash_net_NetConnection_defaultObjectEncoding_get = 1;
const int flash_net_NetConnection_defaultObjectEncoding_set = 2;
const int flash_net_NetConnection_NetConnection = 3;
const int flash_net_NetConnection_connected_get = 4;
const int flash_net_NetConnection_uri_get = 5;
const int flash_net_NetConnection_close = 6;
const int flash_net_NetConnection_addHeader = 7;
const int flash_net_NetConnection_call = 8;
const int flash_net_NetConnection_connect = 9;
const int flash_net_NetConnection_client_get = 10;
const int flash_net_NetConnection_client_set = 11;
const int flash_net_NetConnection_objectEncoding_get = 12;
const int flash_net_NetConnection_objectEncoding_set = 13;
const int flash_net_NetConnection_proxyType_get = 14;
const int flash_net_NetConnection_proxyType_set = 15;
const int flash_net_NetConnection_connectedProxyType_get = 16;
const int flash_net_NetConnection_usingTLS_get = 17;
const int flash_net_NetConnection_protocol_get = 18;
const int flash_net_NetConnection_maxPeerConnections_get = 19;
const int flash_net_NetConnection_maxPeerConnections_set = 20;
const int flash_net_NetConnection_nearID_get = 21;
const int flash_net_NetConnection_farID_get = 22;
const int flash_net_NetConnection_nearNonce_get = 23;
const int flash_net_NetConnection_farNonce_get = 24;
const int flash_net_NetConnection_unconnectedPeerStreams_get = 25;
const int abcclass_flash_net_NetConnection = 0;
extern const int NetConnection_abc_length;
extern const int NetConnection_abc_method_count;
extern const int NetConnection_abc_class_count;
extern const int NetConnection_abc_script_count;
extern const unsigned char NetConnection_abc_data[];
