const int flash_net_Socket_bytesAvailable_get = 4;
const int flash_net_Socket_connected_get = 5;
const int flash_net_Socket_objectEncoding_get = 6;
const int flash_net_Socket_objectEncoding_set = 7;
const int flash_net_Socket_endian_get = 8;
const int flash_net_Socket_endian_set = 9;
const int flash_net_Socket_bytesPending_get = 10;
const int flash_net_Socket_readBytes = 12;
const int flash_net_Socket_writeBytes = 13;
const int flash_net_Socket_writeBoolean = 14;
const int flash_net_Socket_writeByte = 15;
const int flash_net_Socket_writeShort = 16;
const int flash_net_Socket_writeInt = 17;
const int flash_net_Socket_writeUnsignedInt = 18;
const int flash_net_Socket_writeFloat = 19;
const int flash_net_Socket_writeDouble = 20;
const int flash_net_Socket_writeMultiByte = 21;
const int flash_net_Socket_writeUTF = 22;
const int flash_net_Socket_writeUTFBytes = 23;
const int flash_net_Socket_readBoolean = 24;
const int flash_net_Socket_readByte = 25;
const int flash_net_Socket_readUnsignedByte = 26;
const int flash_net_Socket_readShort = 27;
const int flash_net_Socket_readUnsignedShort = 28;
const int flash_net_Socket_readInt = 29;
const int flash_net_Socket_readUnsignedInt = 30;
const int flash_net_Socket_readFloat = 31;
const int flash_net_Socket_readDouble = 32;
const int flash_net_Socket_readMultiByte = 33;
const int flash_net_Socket_readUTF = 34;
const int flash_net_Socket_readUTFBytes = 35;
const int flash_net_Socket_flush = 37;
const int flash_net_Socket_writeObject = 38;
const int flash_net_Socket_readObject = 39;
const int abcclass_flash_net_Socket = 0;
extern const int Socket_abc_length;
extern const int Socket_abc_method_count;
extern const int Socket_abc_class_count;
extern const int Socket_abc_script_count;
extern const unsigned char Socket_abc_data[];
