const int flash_net_URLLoader_URLLoader = 1;
const int flash_net_URLLoader_addEventListener = 2;
const int flash_net_URLLoader_load = 3;
const int flash_net_URLLoader_close = 4;
const int abcclass_flash_net_URLLoader = 0;
extern const int URLLoader_abc_length;
extern const int URLLoader_abc_method_count;
extern const int URLLoader_abc_class_count;
extern const int URLLoader_abc_script_count;
extern const unsigned char URLLoader_abc_data[];
