const int flash_net_URLRequest_URLRequest = 1;
const int flash_net_URLRequest_url_get = 2;
const int flash_net_URLRequest_url_set = 3;
const int flash_net_URLRequest_data_get = 4;
const int flash_net_URLRequest_data_set = 5;
const int flash_net_URLRequest_method_get = 6;
const int flash_net_URLRequest_method_set = 7;
const int flash_net_URLRequest_contentType_get = 8;
const int flash_net_URLRequest_contentType_set = 9;
const int flash_net_URLRequest_requestHeaders_get = 10;
const int flash_net_URLRequest_requestHeaders_set = 11;
const int flash_net_URLRequest_digest_get = 12;
const int flash_net_URLRequest_digest_set = 13;
const int abcclass_flash_net_URLRequest = 0;
extern const int URLRequest_abc_length;
extern const int URLRequest_abc_method_count;
extern const int URLRequest_abc_class_count;
extern const int URLRequest_abc_script_count;
extern const unsigned char URLRequest_abc_data[];
