const int flash_net_URLStream_URLStream = 1;
const int flash_net_URLStream_connected_get = 2;
const int flash_net_URLStream_bytesAvailable_get = 3;
const int flash_net_URLStream_objectEncoding_get = 4;
const int flash_net_URLStream_objectEncoding_set = 5;
const int flash_net_URLStream_endian_get = 6;
const int flash_net_URLStream_endian_set = 7;
const int flash_net_URLStream_diskCacheEnabled_get = 8;
const int flash_net_URLStream_position_get = 9;
const int flash_net_URLStream_position_set = 10;
const int flash_net_URLStream_length_get = 11;
const int flash_net_URLStream_load = 12;
const int flash_net_URLStream_readBytes = 13;
const int flash_net_URLStream_readBoolean = 14;
const int flash_net_URLStream_readByte = 15;
const int flash_net_URLStream_readUnsignedByte = 16;
const int flash_net_URLStream_readShort = 17;
const int flash_net_URLStream_readUnsignedShort = 18;
const int flash_net_URLStream_readUnsignedInt = 19;
const int flash_net_URLStream_readInt = 20;
const int flash_net_URLStream_readFloat = 21;
const int flash_net_URLStream_readDouble = 22;
const int flash_net_URLStream_readMultiByte = 23;
const int flash_net_URLStream_readUTF = 24;
const int flash_net_URLStream_readUTFBytes = 25;
const int flash_net_URLStream_close = 26;
const int flash_net_URLStream_readObject = 27;
const int flash_net_URLStream_stop = 28;
const int abcclass_flash_net_URLStream = 0;
extern const int URLStream_abc_length;
extern const int URLStream_abc_method_count;
extern const int URLStream_abc_class_count;
extern const int URLStream_abc_script_count;
extern const unsigned char URLStream_abc_data[];
