const int avmplus_File_exists = 1;
const int avmplus_File_read = 2;
const int avmplus_File_write = 3;
const int avmplus_File_readByteArray = 4;
const int avmplus_File_writeByteArray = 5;
const int abcclass_avmplus_File = 0;
const int avmplus_System_private_getArgv = 8;
const int abcclass_avmplus_System = 1;
const int abcpackage_avmplus_as = 0;
extern const int ../../../build/libs/avmplus_abc_length;
extern const int ../../../build/libs/avmplus_abc_method_count;
extern const int ../../../build/libs/avmplus_abc_class_count;
extern const int ../../../build/libs/avmplus_abc_script_count;
extern const unsigned char ../../../build/libs/avmplus_abc_data[];
