const int flash_ui_ContextMenuBuiltInItems_ContextMenuBuiltInItems = 1;
const int flash_ui_ContextMenuBuiltInItems_save_get = 2;
const int flash_ui_ContextMenuBuiltInItems_save_set = 3;
const int flash_ui_ContextMenuBuiltInItems_zoom_get = 4;
const int flash_ui_ContextMenuBuiltInItems_zoom_set = 5;
const int flash_ui_ContextMenuBuiltInItems_quality_get = 6;
const int flash_ui_ContextMenuBuiltInItems_quality_set = 7;
const int flash_ui_ContextMenuBuiltInItems_play_get = 8;
const int flash_ui_ContextMenuBuiltInItems_play_set = 9;
const int flash_ui_ContextMenuBuiltInItems_loop_get = 10;
const int flash_ui_ContextMenuBuiltInItems_loop_set = 11;
const int flash_ui_ContextMenuBuiltInItems_rewind_get = 12;
const int flash_ui_ContextMenuBuiltInItems_rewind_set = 13;
const int flash_ui_ContextMenuBuiltInItems_forwardAndBack_get = 14;
const int flash_ui_ContextMenuBuiltInItems_forwardAndBack_set = 15;
const int flash_ui_ContextMenuBuiltInItems_print_get = 16;
const int flash_ui_ContextMenuBuiltInItems_print_set = 17;
const int flash_ui_ContextMenuBuiltInItems_clone = 18;
const int abcclass_flash_ui_ContextMenuBuiltInItems = 0;
extern const int ContextMenuBuiltInItems_abc_length;
extern const int ContextMenuBuiltInItems_abc_method_count;
extern const int ContextMenuBuiltInItems_abc_class_count;
extern const int ContextMenuBuiltInItems_abc_script_count;
extern const unsigned char ContextMenuBuiltInItems_abc_data[];
