const int flash_ui_ContextMenu_isSupported_get = 1;
const int flash_ui_ContextMenu_ContextMenu = 2;
const int flash_ui_ContextMenu_builtInItems_get = 3;
const int flash_ui_ContextMenu_builtInItems_set = 4;
const int flash_ui_ContextMenu_customItems_get = 5;
const int flash_ui_ContextMenu_customItems_set = 6;
const int flash_ui_ContextMenu_link_get = 7;
const int flash_ui_ContextMenu_link_set = 8;
const int flash_ui_ContextMenu_clipboardMenu_get = 9;
const int flash_ui_ContextMenu_clipboardMenu_set = 10;
const int flash_ui_ContextMenu_clipboardItems_get = 11;
const int flash_ui_ContextMenu_clipboardItems_set = 12;
const int flash_ui_ContextMenu_hideBuiltInItems = 13;
const int flash_ui_ContextMenu_clone = 14;
const int flash_ui_ContextMenu_private_cloneLinkAndClipboardProperties = 15;
const int abcclass_flash_ui_ContextMenu = 0;
extern const int ContextMenu_abc_length;
extern const int ContextMenu_abc_method_count;
extern const int ContextMenu_abc_class_count;
extern const int ContextMenu_abc_script_count;
extern const unsigned char ContextMenu_abc_data[];
