const int flash_ui_GameInputControl_numValues_get = 2;
const int flash_ui_GameInputControl_index_get = 3;
const int flash_ui_GameInputControl_relative_get = 4;
const int flash_ui_GameInputControl_type_get = 5;
const int flash_ui_GameInputControl_hand_get = 6;
const int flash_ui_GameInputControl_finger_get = 7;
const int flash_ui_GameInputControl_device_get = 8;
const int flash_ui_GameInputControl_getValueAt = 9;
const int abcclass_flash_ui_GameInputControl = 0;
extern const int GameInputControl_abc_length;
extern const int GameInputControl_abc_method_count;
extern const int GameInputControl_abc_class_count;
extern const int GameInputControl_abc_script_count;
extern const unsigned char GameInputControl_abc_data[];
