const int flash_ui_MouseCursorData_data_get = 2;
const int flash_ui_MouseCursorData_data_set = 3;
const int flash_ui_MouseCursorData_hotSpot_get = 4;
const int flash_ui_MouseCursorData_hotSpot_set = 5;
const int flash_ui_MouseCursorData_frameRate_get = 6;
const int flash_ui_MouseCursorData_frameRate_set = 7;
const int abcclass_flash_ui_MouseCursorData = 0;
extern const int MouseCursorData_abc_length;
extern const int MouseCursorData_abc_method_count;
extern const int MouseCursorData_abc_class_count;
extern const int MouseCursorData_abc_script_count;
extern const unsigned char MouseCursorData_abc_data[];
