const int flash_ui_Multitouch_inputMode_get = 1;
const int flash_ui_Multitouch_inputMode_set = 2;
const int flash_ui_Multitouch_supportsTouchEvents_get = 3;
const int flash_ui_Multitouch_supportsGestureEvents_get = 4;
const int flash_ui_Multitouch_supportedGestures_get = 5;
const int flash_ui_Multitouch_maxTouchPoints_get = 6;
const int flash_ui_Multitouch_mapTouchToMouse_get = 7;
const int flash_ui_Multitouch_mapTouchToMouse_set = 8;
const int abcclass_flash_ui_Multitouch = 0;
extern const int Multitouch_abc_length;
extern const int Multitouch_abc_method_count;
extern const int Multitouch_abc_class_count;
extern const int Multitouch_abc_script_count;
extern const unsigned char Multitouch_abc_data[];
