const int flash_display_Bitmap_Bitmap = 1;
const int flash_display_Bitmap_pixelSnapping_get = 2;
const int flash_display_Bitmap_pixelSnapping_set = 3;
const int flash_display_Bitmap_smoothing_get = 4;
const int flash_display_Bitmap_smoothing_set = 5;
const int flash_display_Bitmap_bitmapData_get = 6;
const int flash_display_Bitmap_bitmapData_set = 7;
const int abcclass_flash_display_Bitmap = 0;
extern const int Bitmap_abc_length;
extern const int Bitmap_abc_method_count;
extern const int Bitmap_abc_class_count;
extern const int Bitmap_abc_script_count;
extern const unsigned char Bitmap_abc_data[];
