const int flash_display_DisplayObjectContainer_DisplayObjectContainer = 1;
const int flash_display_DisplayObjectContainer_numChildren_get = 2;
const int flash_display_DisplayObjectContainer_textSnapshot_get = 3;
const int flash_display_DisplayObjectContainer_tabChildren_get = 4;
const int flash_display_DisplayObjectContainer_tabChildren_set = 5;
const int flash_display_DisplayObjectContainer_mouseChildren_get = 6;
const int flash_display_DisplayObjectContainer_mouseChildren_set = 7;
const int flash_display_DisplayObjectContainer_addChild = 8;
const int flash_display_DisplayObjectContainer_addChildAt = 9;
const int flash_display_DisplayObjectContainer_removeChild = 10;
const int flash_display_DisplayObjectContainer_removeChildAt = 11;
const int flash_display_DisplayObjectContainer_getChildIndex = 12;
const int flash_display_DisplayObjectContainer_setChildIndex = 13;
const int flash_display_DisplayObjectContainer_getChildAt = 14;
const int flash_display_DisplayObjectContainer_getChildByName = 15;
const int flash_display_DisplayObjectContainer_getObjectsUnderPoint = 16;
const int flash_display_DisplayObjectContainer_areInaccessibleObjectsUnderPoint = 17;
const int flash_display_DisplayObjectContainer_contains = 18;
const int flash_display_DisplayObjectContainer_swapChildrenAt = 19;
const int flash_display_DisplayObjectContainer_swapChildren = 20;
const int flash_display_DisplayObjectContainer_removeChildren = 21;
const int abcclass_flash_display_DisplayObjectContainer = 0;
extern const int DisplayObjectContainer_abc_length;
extern const int DisplayObjectContainer_abc_method_count;
extern const int DisplayObjectContainer_abc_class_count;
extern const int DisplayObjectContainer_abc_script_count;
extern const unsigned char DisplayObjectContainer_abc_data[];
