const int flash_display_InteractiveObject_InteractiveObject = 1;
const int flash_display_InteractiveObject_tabEnabled_get = 2;
const int flash_display_InteractiveObject_tabEnabled_set = 3;
const int flash_display_InteractiveObject_tabIndex_get = 4;
const int flash_display_InteractiveObject_tabIndex_set = 5;
const int flash_display_InteractiveObject_focusRect_get = 6;
const int flash_display_InteractiveObject_focusRect_set = 7;
const int flash_display_InteractiveObject_mouseEnabled_get = 8;
const int flash_display_InteractiveObject_mouseEnabled_set = 9;
const int flash_display_InteractiveObject_doubleClickEnabled_get = 10;
const int flash_display_InteractiveObject_doubleClickEnabled_set = 11;
const int flash_display_InteractiveObject_accessibilityImplementation_get = 12;
const int flash_display_InteractiveObject_accessibilityImplementation_set = 13;
const int flash_display_InteractiveObject_softKeyboardInputAreaOfInterest_get = 14;
const int flash_display_InteractiveObject_softKeyboardInputAreaOfInterest_set = 15;
const int flash_display_InteractiveObject_needsSoftKeyboard_get = 16;
const int flash_display_InteractiveObject_needsSoftKeyboard_set = 17;
const int flash_display_InteractiveObject_contextMenu_get = 18;
const int flash_display_InteractiveObject_contextMenu_set = 19;
const int flash_display_InteractiveObject_requestSoftKeyboard = 20;
const int abcclass_flash_display_InteractiveObject = 0;
extern const int InteractiveObject_abc_length;
extern const int InteractiveObject_abc_method_count;
extern const int InteractiveObject_abc_class_count;
extern const int InteractiveObject_abc_script_count;
extern const unsigned char InteractiveObject_abc_data[];
