const int flash_display_Scene_Scene = 1;
const int flash_display_Scene_name_get = 2;
const int flash_display_Scene_labels_get = 3;
const int flash_display_Scene_numFrames_get = 4;
const int abcclass_flash_display_Scene = 0;
extern const int Scene_abc_length;
extern const int Scene_abc_method_count;
extern const int Scene_abc_class_count;
extern const int Scene_abc_script_count;
extern const unsigned char Scene_abc_data[];
