const int flash_display_Stage3D_context3D_get = 2;
const int flash_display_Stage3D_x_get = 3;
const int flash_display_Stage3D_x_set = 4;
const int flash_display_Stage3D_y_get = 5;
const int flash_display_Stage3D_y_set = 6;
const int flash_display_Stage3D_visible_get = 7;
const int flash_display_Stage3D_visible_set = 8;
const int flash_display_Stage3D_requestContext3D = 9;
const int abcclass_flash_display_Stage3D = 0;
extern const int Stage3D_abc_length;
extern const int Stage3D_abc_method_count;
extern const int Stage3D_abc_class_count;
extern const int Stage3D_abc_script_count;
extern const unsigned char Stage3D_abc_data[];
