const int flash_globalization_NumberParseResult_value_get = 2;
const int flash_globalization_NumberParseResult_startIndex_get = 3;
const int flash_globalization_NumberParseResult_endIndex_get = 4;
const int flash_globalization_NumberParseResult_private_ctor = 5;
const int abcclass_flash_globalization_NumberParseResult = 0;
extern const int NumberParseResult_abc_length;
extern const int NumberParseResult_abc_method_count;
extern const int NumberParseResult_abc_class_count;
extern const int NumberParseResult_abc_script_count;
extern const unsigned char NumberParseResult_abc_data[];
