const int flash_globalization_NumberFormatter_getAvailableLocaleIDNames = 1;
const int flash_globalization_NumberFormatter_lastOperationStatus_get = 3;
const int flash_globalization_NumberFormatter_requestedLocaleIDName_get = 4;
const int flash_globalization_NumberFormatter_actualLocaleIDName_get = 5;
const int flash_globalization_NumberFormatter_fractionalDigits_get = 6;
const int flash_globalization_NumberFormatter_fractionalDigits_set = 7;
const int flash_globalization_NumberFormatter_useGrouping_get = 8;
const int flash_globalization_NumberFormatter_useGrouping_set = 9;
const int flash_globalization_NumberFormatter_groupingPattern_get = 10;
const int flash_globalization_NumberFormatter_groupingPattern_set = 11;
const int flash_globalization_NumberFormatter_digitsType_get = 12;
const int flash_globalization_NumberFormatter_digitsType_set = 13;
const int flash_globalization_NumberFormatter_decimalSeparator_get = 14;
const int flash_globalization_NumberFormatter_decimalSeparator_set = 15;
const int flash_globalization_NumberFormatter_groupingSeparator_get = 16;
const int flash_globalization_NumberFormatter_groupingSeparator_set = 17;
const int flash_globalization_NumberFormatter_negativeSymbol_get = 18;
const int flash_globalization_NumberFormatter_negativeSymbol_set = 19;
const int flash_globalization_NumberFormatter_negativeNumberFormat_get = 20;
const int flash_globalization_NumberFormatter_negativeNumberFormat_set = 21;
const int flash_globalization_NumberFormatter_leadingZero_get = 22;
const int flash_globalization_NumberFormatter_leadingZero_set = 23;
const int flash_globalization_NumberFormatter_trailingZeros_get = 24;
const int flash_globalization_NumberFormatter_trailingZeros_set = 25;
const int flash_globalization_NumberFormatter_parse = 26;
const int flash_globalization_NumberFormatter_parseNumber = 27;
const int flash_globalization_NumberFormatter_formatInt = 28;
const int flash_globalization_NumberFormatter_formatUint = 29;
const int flash_globalization_NumberFormatter_formatNumber = 30;
const int flash_globalization_NumberFormatter_private_ctor = 31;
const int abcclass_flash_globalization_NumberFormatter = 0;
extern const int NumberFormatter_abc_length;
extern const int NumberFormatter_abc_method_count;
extern const int NumberFormatter_abc_class_count;
extern const int NumberFormatter_abc_script_count;
extern const unsigned char NumberFormatter_abc_data[];
