const int flash_globalization_StringTools_getAvailableLocaleIDNames = 1;
const int flash_globalization_StringTools_lastOperationStatus_get = 3;
const int flash_globalization_StringTools_requestedLocaleIDName_get = 4;
const int flash_globalization_StringTools_actualLocaleIDName_get = 5;
const int flash_globalization_StringTools_toLowerCase = 6;
const int flash_globalization_StringTools_toUpperCase = 7;
const int flash_globalization_StringTools_private_ctor = 8;
const int abcclass_flash_globalization_StringTools = 0;
extern const int StringTools_abc_length;
extern const int StringTools_abc_method_count;
extern const int StringTools_abc_class_count;
extern const int StringTools_abc_script_count;
extern const unsigned char StringTools_abc_data[];
