const int flash_text_TextRenderer_antiAliasType_get = 1;
const int flash_text_TextRenderer_antiAliasType_set = 2;
const int flash_text_TextRenderer_maxLevel_get = 3;
const int flash_text_TextRenderer_maxLevel_set = 4;
const int flash_text_TextRenderer_displayMode_get = 5;
const int flash_text_TextRenderer_displayMode_set = 6;
const int flash_text_TextRenderer_setAdvancedAntiAliasingTable = 7;
const int abcclass_flash_text_TextRenderer = 0;
extern const int TextRenderer_abc_length;
extern const int TextRenderer_abc_method_count;
extern const int TextRenderer_abc_class_count;
extern const int TextRenderer_abc_script_count;
extern const unsigned char TextRenderer_abc_data[];
