const int flash_text_TextSnapshot_charCount_get = 2;
const int flash_text_TextSnapshot_findText = 3;
const int flash_text_TextSnapshot_getSelected = 4;
const int flash_text_TextSnapshot_getSelectedText = 5;
const int flash_text_TextSnapshot_getText = 6;
const int flash_text_TextSnapshot_getTextRunInfo = 7;
const int flash_text_TextSnapshot_hitTestTextNearPos = 8;
const int flash_text_TextSnapshot_setSelectColor = 9;
const int flash_text_TextSnapshot_setSelected = 10;
const int abcclass_flash_text_TextSnapshot = 0;
extern const int TextSnapshot_abc_length;
extern const int TextSnapshot_abc_method_count;
extern const int TextSnapshot_abc_class_count;
extern const int TextSnapshot_abc_script_count;
extern const unsigned char TextSnapshot_abc_data[];
