const int flash_trace_Trace_setLevel = 1;
const int flash_trace_Trace_getLevel = 2;
const int flash_trace_Trace_setListener = 3;
const int flash_trace_Trace_getListener = 4;
const int abcclass_flash_trace_Trace = 0;
extern const int Trace_abc_length;
extern const int Trace_abc_method_count;
extern const int Trace_abc_class_count;
extern const int Trace_abc_script_count;
extern const unsigned char Trace_abc_data[];
