const int flash_display_BitmapData_BitmapData = 1;
const int flash_display_BitmapData_width_get = 2;
const int flash_display_BitmapData_height_get = 3;
const int flash_display_BitmapData_transparent_get = 4;
const int flash_display_BitmapData_rect_get = 5;
const int flash_display_BitmapData_clone = 6;
const int flash_display_BitmapData_getPixel = 7;
const int flash_display_BitmapData_getPixel32 = 8;
const int flash_display_BitmapData_setPixel = 9;
const int flash_display_BitmapData_setPixel32 = 10;
const int flash_display_BitmapData_applyFilter = 11;
const int flash_display_BitmapData_colorTransform = 12;
const int flash_display_BitmapData_compare = 13;
const int flash_display_BitmapData_copyChannel = 14;
const int flash_display_BitmapData_copyPixels = 15;
const int flash_display_BitmapData_dispose = 16;
const int flash_display_BitmapData_draw = 17;
const int flash_display_BitmapData_drawWithQuality = 18;
const int flash_display_BitmapData_fillRect = 19;
const int flash_display_BitmapData_floodFill = 20;
const int flash_display_BitmapData_generateFilterRect = 21;
const int flash_display_BitmapData_getColorBoundsRect = 22;
const int flash_display_BitmapData_getPixels = 23;
const int flash_display_BitmapData_copyPixelsToByteArray = 24;
const int flash_display_BitmapData_getVector = 25;
const int flash_display_BitmapData_hitTest = 26;
const int flash_display_BitmapData_merge = 27;
const int flash_display_BitmapData_noise = 28;
const int flash_display_BitmapData_paletteMap = 29;
const int flash_display_BitmapData_perlinNoise = 30;
const int flash_display_BitmapData_pixelDissolve = 31;
const int flash_display_BitmapData_scroll = 32;
const int flash_display_BitmapData_setPixels = 33;
const int flash_display_BitmapData_setVector = 34;
const int flash_display_BitmapData_threshold = 35;
const int flash_display_BitmapData_lock = 36;
const int flash_display_BitmapData_unlock = 37;
const int flash_display_BitmapData_histogram = 38;
const int flash_display_BitmapData_encode = 39;
const int abcclass_flash_display_BitmapData = 0;
extern const int BitmapData_abc_length;
extern const int BitmapData_abc_method_count;
extern const int BitmapData_abc_class_count;
extern const int BitmapData_abc_script_count;
extern const unsigned char BitmapData_abc_data[];
