const int flash_display_Graphics_Graphics = 1;
const int flash_display_Graphics_clear = 2;
const int flash_display_Graphics_beginFill = 3;
const int flash_display_Graphics_beginGradientFill = 4;
const int flash_display_Graphics_beginBitmapFill = 5;
const int flash_display_Graphics_lineGradientStyle = 6;
const int flash_display_Graphics_lineStyle = 7;
const int flash_display_Graphics_drawRect = 8;
const int flash_display_Graphics_drawRoundRect = 9;
const int flash_display_Graphics_drawRoundRectComplex = 10;
const int flash_display_Graphics_drawCircle = 11;
const int flash_display_Graphics_drawEllipse = 12;
const int flash_display_Graphics_moveTo = 13;
const int flash_display_Graphics_lineTo = 14;
const int flash_display_Graphics_curveTo = 15;
const int flash_display_Graphics_cubicCurveTo = 16;
const int flash_display_Graphics_endFill = 17;
const int flash_display_Graphics_copyFrom = 18;
const int flash_display_Graphics_lineBitmapStyle = 19;
const int flash_display_Graphics_drawPath = 20;
const int flash_display_Graphics_drawTriangles = 21;
const int flash_display_Graphics_drawGraphicsData = 22;
const int abcclass_flash_display_Graphics = 0;
extern const int Graphics_abc_length;
extern const int Graphics_abc_method_count;
extern const int Graphics_abc_class_count;
extern const int Graphics_abc_script_count;
extern const unsigned char Graphics_abc_data[];
