const int flash_display_LoaderInfo_getLoaderInfoByDefinition = 1;
const int flash_display_LoaderInfo_LoaderInfo = 2;
const int flash_display_LoaderInfo_loaderURL_get = 3;
const int flash_display_LoaderInfo_url_get = 4;
const int flash_display_LoaderInfo_isURLInaccessible_get = 5;
const int flash_display_LoaderInfo_bytesLoaded_get = 6;
const int flash_display_LoaderInfo_bytesTotal_get = 7;
const int flash_display_LoaderInfo_applicationDomain_get = 8;
const int flash_display_LoaderInfo_swfVersion_get = 9;
const int flash_display_LoaderInfo_actionScriptVersion_get = 10;
const int flash_display_LoaderInfo_frameRate_get = 11;
const int flash_display_LoaderInfo_parameters_get = 12;
const int flash_display_LoaderInfo_width_get = 13;
const int flash_display_LoaderInfo_height_get = 14;
const int flash_display_LoaderInfo_contentType_get = 15;
const int flash_display_LoaderInfo_sharedEvents_get = 16;
const int flash_display_LoaderInfo_parentSandboxBridge_get = 17;
const int flash_display_LoaderInfo_parentSandboxBridge_set = 18;
const int flash_display_LoaderInfo_childSandboxBridge_get = 19;
const int flash_display_LoaderInfo_childSandboxBridge_set = 20;
const int flash_display_LoaderInfo_sameDomain_get = 21;
const int flash_display_LoaderInfo_childAllowsParent_get = 22;
const int flash_display_LoaderInfo_parentAllowsChild_get = 23;
const int flash_display_LoaderInfo_loader_get = 24;
const int flash_display_LoaderInfo_content_get = 25;
const int flash_display_LoaderInfo_bytes_get = 26;
const int flash_display_LoaderInfo_uncaughtErrorEvents_get = 27;
const int abcclass_flash_display_LoaderInfo = 0;
extern const int LoaderInfo_abc_length;
extern const int LoaderInfo_abc_method_count;
extern const int LoaderInfo_abc_class_count;
extern const int LoaderInfo_abc_script_count;
extern const unsigned char LoaderInfo_abc_data[];
