const int flash_display_MovieClip_MovieClip = 1;
const int flash_display_MovieClip_currentFrame_get = 2;
const int flash_display_MovieClip_framesLoaded_get = 3;
const int flash_display_MovieClip_totalFrames_get = 4;
const int flash_display_MovieClip_trackAsMenu_get = 5;
const int flash_display_MovieClip_trackAsMenu_set = 6;
const int flash_display_MovieClip_scenes_get = 7;
const int flash_display_MovieClip_currentScene_get = 8;
const int flash_display_MovieClip_currentLabel_get = 9;
const int flash_display_MovieClip_currentFrameLabel_get = 10;
const int flash_display_MovieClip_currentLabels_get = 11;
const int flash_display_MovieClip_enabled_get = 12;
const int flash_display_MovieClip_enabled_set = 13;
const int flash_display_MovieClip_isPlaying_get = 14;
const int flash_display_MovieClip_play = 15;
const int flash_display_MovieClip_stop = 16;
const int flash_display_MovieClip_nextFrame = 17;
const int flash_display_MovieClip_prevFrame = 18;
const int flash_display_MovieClip_gotoAndPlay = 19;
const int flash_display_MovieClip_gotoAndStop = 20;
const int flash_display_MovieClip_addFrameScript = 21;
const int flash_display_MovieClip_prevScene = 22;
const int flash_display_MovieClip_nextScene = 23;
const int abcclass_flash_display_MovieClip = 0;
extern const int MovieClip_abc_length;
extern const int MovieClip_abc_method_count;
extern const int MovieClip_abc_class_count;
extern const int MovieClip_abc_script_count;
extern const unsigned char MovieClip_abc_data[];
