const int flash_display_SimpleButton_SimpleButton = 1;
const int flash_display_SimpleButton_useHandCursor_get = 2;
const int flash_display_SimpleButton_useHandCursor_set = 3;
const int flash_display_SimpleButton_enabled_get = 4;
const int flash_display_SimpleButton_enabled_set = 5;
const int flash_display_SimpleButton_trackAsMenu_get = 6;
const int flash_display_SimpleButton_trackAsMenu_set = 7;
const int flash_display_SimpleButton_upState_get = 8;
const int flash_display_SimpleButton_upState_set = 9;
const int flash_display_SimpleButton_overState_get = 10;
const int flash_display_SimpleButton_overState_set = 11;
const int flash_display_SimpleButton_downState_get = 12;
const int flash_display_SimpleButton_downState_set = 13;
const int flash_display_SimpleButton_hitTestState_get = 14;
const int flash_display_SimpleButton_hitTestState_set = 15;
const int flash_display_SimpleButton_soundTransform_get = 16;
const int flash_display_SimpleButton_soundTransform_set = 17;
const int abcclass_flash_display_SimpleButton = 0;
extern const int SimpleButton_abc_length;
extern const int SimpleButton_abc_method_count;
extern const int SimpleButton_abc_class_count;
extern const int SimpleButton_abc_script_count;
extern const unsigned char SimpleButton_abc_data[];
