const int flash_display_Sprite_Sprite = 1;
const int flash_display_Sprite_graphics_get = 2;
const int flash_display_Sprite_buttonMode_get = 3;
const int flash_display_Sprite_buttonMode_set = 4;
const int flash_display_Sprite_dropTarget_get = 5;
const int flash_display_Sprite_hitArea_get = 6;
const int flash_display_Sprite_hitArea_set = 7;
const int flash_display_Sprite_useHandCursor_get = 8;
const int flash_display_Sprite_useHandCursor_set = 9;
const int flash_display_Sprite_soundTransform_get = 10;
const int flash_display_Sprite_soundTransform_set = 11;
const int flash_display_Sprite_startDrag = 12;
const int flash_display_Sprite_stopDrag = 13;
const int flash_display_Sprite_startTouchDrag = 14;
const int flash_display_Sprite_stopTouchDrag = 15;
const int abcclass_flash_display_Sprite = 0;
extern const int Sprite_abc_length;
extern const int Sprite_abc_method_count;
extern const int Sprite_abc_class_count;
extern const int Sprite_abc_script_count;
extern const unsigned char Sprite_abc_data[];
