const int flash_display3D_Context3D_driverInfo_get = 2;
const int flash_display3D_Context3D_enableErrorChecking_get = 3;
const int flash_display3D_Context3D_enableErrorChecking_set = 4;
const int flash_display3D_Context3D_dispose = 5;
const int flash_display3D_Context3D_configureBackBuffer = 6;
const int flash_display3D_Context3D_clear = 7;
const int flash_display3D_Context3D_drawTriangles = 8;
const int flash_display3D_Context3D_present = 9;
const int flash_display3D_Context3D_setProgram = 10;
const int flash_display3D_Context3D_setProgramConstantsFromVector = 11;
const int flash_display3D_Context3D_setProgramConstantsFromMatrix = 12;
const int flash_display3D_Context3D_setProgramConstantsFromByteArray = 13;
const int flash_display3D_Context3D_setVertexBufferAt = 14;
const int flash_display3D_Context3D_setBlendFactors = 15;
const int flash_display3D_Context3D_setColorMask = 16;
const int flash_display3D_Context3D_setDepthTest = 17;
const int flash_display3D_Context3D_setCulling = 21;
const int flash_display3D_Context3D_setStencilActions = 22;
const int flash_display3D_Context3D_setStencilReferenceValue = 23;
const int flash_display3D_Context3D_setScissorRectangle = 24;
const int flash_display3D_Context3D_createVertexBuffer = 25;
const int flash_display3D_Context3D_createIndexBuffer = 26;
const int flash_display3D_Context3D_createTexture = 27;
const int flash_display3D_Context3D_createCubeTexture = 28;
const int flash_display3D_Context3D_createProgram = 29;
const int flash_display3D_Context3D_drawToBitmapData = 30;
const int flash_display3D_Context3D_private_setRenderToTextureInternal = 31;
const int flash_display3D_Context3D_private_setTextureInternal = 32;
const int flash_display3D_Context3D_private_setCubeTextureInternal = 33;
const int abcclass_flash_display3D_Context3D = 0;
extern const int Context3D_abc_length;
extern const int Context3D_abc_method_count;
extern const int Context3D_abc_class_count;
extern const int Context3D_abc_script_count;
extern const unsigned char Context3D_abc_data[];
