const int flash_media_Camera_names_get = 1;
const int flash_media_Camera_isSupported_get = 2;
const int flash_media_Camera_getCamera = 3;
const int flash_media_Camera_flash_media__scanHardware = 4;
const int flash_media_Camera_activityLevel_get = 6;
const int flash_media_Camera_bandwidth_get = 7;
const int flash_media_Camera_currentFPS_get = 8;
const int flash_media_Camera_fps_get = 9;
const int flash_media_Camera_height_get = 10;
const int flash_media_Camera_index_get = 11;
const int flash_media_Camera_keyFrameInterval_get = 12;
const int flash_media_Camera_loopback_get = 13;
const int flash_media_Camera_motionLevel_get = 14;
const int flash_media_Camera_motionTimeout_get = 15;
const int flash_media_Camera_muted_get = 16;
const int flash_media_Camera_name_get = 17;
const int flash_media_Camera_quality_get = 18;
const int flash_media_Camera_width_get = 19;
const int flash_media_Camera_setCursor = 20;
const int flash_media_Camera_setKeyFrameInterval = 21;
const int flash_media_Camera_setLoopback = 22;
const int flash_media_Camera_setMode = 23;
const int flash_media_Camera_setMotionLevel = 24;
const int flash_media_Camera_setQuality = 25;
const int flash_media_Camera_drawToBitmapData = 26;
const int flash_media_Camera_copyToByteArray = 27;
const int flash_media_Camera_copyToVector = 28;
const int abcclass_flash_media_Camera = 0;
extern const int Camera_abc_length;
extern const int Camera_abc_method_count;
extern const int Camera_abc_class_count;
extern const int Camera_abc_script_count;
extern const unsigned char Camera_abc_data[];
