const int flash_media_Microphone_names_get = 1;
const int flash_media_Microphone_isSupported_get = 2;
const int flash_media_Microphone_getMicrophone = 3;
const int flash_media_Microphone_getEnhancedMicrophone = 4;
const int flash_media_Microphone_rate_get = 6;
const int flash_media_Microphone_rate_set = 7;
const int flash_media_Microphone_codec_get = 8;
const int flash_media_Microphone_codec_set = 9;
const int flash_media_Microphone_framesPerPacket_get = 10;
const int flash_media_Microphone_framesPerPacket_set = 11;
const int flash_media_Microphone_encodeQuality_get = 12;
const int flash_media_Microphone_encodeQuality_set = 13;
const int flash_media_Microphone_noiseSuppressionLevel_get = 14;
const int flash_media_Microphone_noiseSuppressionLevel_set = 15;
const int flash_media_Microphone_enableVAD_get = 16;
const int flash_media_Microphone_enableVAD_set = 17;
const int flash_media_Microphone_activityLevel_get = 18;
const int flash_media_Microphone_gain_get = 19;
const int flash_media_Microphone_gain_set = 20;
const int flash_media_Microphone_index_get = 21;
const int flash_media_Microphone_muted_get = 22;
const int flash_media_Microphone_name_get = 23;
const int flash_media_Microphone_silenceLevel_get = 24;
const int flash_media_Microphone_silenceTimeout_get = 25;
const int flash_media_Microphone_useEchoSuppression_get = 26;
const int flash_media_Microphone_soundTransform_get = 27;
const int flash_media_Microphone_soundTransform_set = 28;
const int flash_media_Microphone_enhancedOptions_get = 29;
const int flash_media_Microphone_enhancedOptions_set = 30;
const int flash_media_Microphone_setSilenceLevel = 31;
const int flash_media_Microphone_setUseEchoSuppression = 32;
const int flash_media_Microphone_setLoopBack = 33;
const int abcclass_flash_media_Microphone = 0;
extern const int Microphone_abc_length;
extern const int Microphone_abc_method_count;
extern const int Microphone_abc_class_count;
extern const int Microphone_abc_script_count;
extern const unsigned char Microphone_abc_data[];
