const int flash_media_SoundMixer_bufferTime_get = 1;
const int flash_media_SoundMixer_bufferTime_set = 2;
const int flash_media_SoundMixer_soundTransform_get = 3;
const int flash_media_SoundMixer_soundTransform_set = 4;
const int flash_media_SoundMixer_audioPlaybackMode_get = 5;
const int flash_media_SoundMixer_audioPlaybackMode_set = 6;
const int flash_media_SoundMixer_useSpeakerphoneForVoice_get = 7;
const int flash_media_SoundMixer_useSpeakerphoneForVoice_set = 8;
const int flash_media_SoundMixer_stopAll = 9;
const int flash_media_SoundMixer_computeSpectrum = 10;
const int flash_media_SoundMixer_areSoundsInaccessible = 11;
const int abcclass_flash_media_SoundMixer = 0;
extern const int SoundMixer_abc_length;
extern const int SoundMixer_abc_method_count;
extern const int SoundMixer_abc_class_count;
extern const int SoundMixer_abc_script_count;
extern const unsigned char SoundMixer_abc_data[];
