const int flash_media_SoundTransform_volume_get = 2;
const int flash_media_SoundTransform_volume_set = 3;
const int flash_media_SoundTransform_leftToLeft_get = 4;
const int flash_media_SoundTransform_leftToLeft_set = 5;
const int flash_media_SoundTransform_leftToRight_get = 6;
const int flash_media_SoundTransform_leftToRight_set = 7;
const int flash_media_SoundTransform_rightToRight_get = 8;
const int flash_media_SoundTransform_rightToRight_set = 9;
const int flash_media_SoundTransform_rightToLeft_get = 10;
const int flash_media_SoundTransform_rightToLeft_set = 11;
const int flash_media_SoundTransform_pan_get = 12;
const int flash_media_SoundTransform_pan_set = 13;
const int abcclass_flash_media_SoundTransform = 0;
extern const int SoundTransform_abc_length;
extern const int SoundTransform_abc_method_count;
extern const int SoundTransform_abc_class_count;
extern const int SoundTransform_abc_script_count;
extern const unsigned char SoundTransform_abc_data[];
