const int flash_media_StageVideo_viewPort_get = 2;
const int flash_media_StageVideo_viewPort_set = 3;
const int flash_media_StageVideo_pan_get = 4;
const int flash_media_StageVideo_pan_set = 5;
const int flash_media_StageVideo_zoom_get = 6;
const int flash_media_StageVideo_zoom_set = 7;
const int flash_media_StageVideo_depth_get = 8;
const int flash_media_StageVideo_depth_set = 9;
const int flash_media_StageVideo_videoWidth_get = 10;
const int flash_media_StageVideo_videoHeight_get = 11;
const int flash_media_StageVideo_colorSpaces_get = 12;
const int flash_media_StageVideo_attachNetStream = 13;
const int flash_media_StageVideo_attachCamera = 14;
const int abcclass_flash_media_StageVideo = 0;
extern const int StageVideo_abc_length;
extern const int StageVideo_abc_method_count;
extern const int StageVideo_abc_class_count;
extern const int StageVideo_abc_script_count;
extern const unsigned char StageVideo_abc_data[];
