const int flash_media_Video_Video = 1;
const int flash_media_Video_deblocking_get = 2;
const int flash_media_Video_deblocking_set = 3;
const int flash_media_Video_smoothing_get = 4;
const int flash_media_Video_smoothing_set = 5;
const int flash_media_Video_videoWidth_get = 6;
const int flash_media_Video_videoHeight_get = 7;
const int flash_media_Video_clear = 8;
const int flash_media_Video_attachNetStream = 9;
const int flash_media_Video_attachCamera = 10;
const int abcclass_flash_media_Video = 0;
extern const int Video_abc_length;
extern const int Video_abc_method_count;
extern const int Video_abc_class_count;
extern const int Video_abc_script_count;
extern const unsigned char Video_abc_data[];
