const int flash_filters_BevelFilter_BevelFilter = 1;
const int flash_filters_BevelFilter_distance_get = 2;
const int flash_filters_BevelFilter_distance_set = 3;
const int flash_filters_BevelFilter_angle_get = 4;
const int flash_filters_BevelFilter_angle_set = 5;
const int flash_filters_BevelFilter_highlightColor_get = 6;
const int flash_filters_BevelFilter_highlightColor_set = 7;
const int flash_filters_BevelFilter_highlightAlpha_get = 8;
const int flash_filters_BevelFilter_highlightAlpha_set = 9;
const int flash_filters_BevelFilter_shadowColor_get = 10;
const int flash_filters_BevelFilter_shadowColor_set = 11;
const int flash_filters_BevelFilter_shadowAlpha_get = 12;
const int flash_filters_BevelFilter_shadowAlpha_set = 13;
const int flash_filters_BevelFilter_blurX_get = 14;
const int flash_filters_BevelFilter_blurX_set = 15;
const int flash_filters_BevelFilter_blurY_get = 16;
const int flash_filters_BevelFilter_blurY_set = 17;
const int flash_filters_BevelFilter_knockout_get = 18;
const int flash_filters_BevelFilter_knockout_set = 19;
const int flash_filters_BevelFilter_quality_get = 20;
const int flash_filters_BevelFilter_quality_set = 21;
const int flash_filters_BevelFilter_strength_get = 22;
const int flash_filters_BevelFilter_strength_set = 23;
const int flash_filters_BevelFilter_type_get = 24;
const int flash_filters_BevelFilter_type_set = 25;
const int flash_filters_BevelFilter_clone = 26;
const int abcclass_flash_filters_BevelFilter = 0;
extern const int BevelFilter_abc_length;
extern const int BevelFilter_abc_method_count;
extern const int BevelFilter_abc_class_count;
extern const int BevelFilter_abc_script_count;
extern const unsigned char BevelFilter_abc_data[];
