const int flash_filters_BlurFilter_BlurFilter = 1;
const int flash_filters_BlurFilter_blurX_get = 2;
const int flash_filters_BlurFilter_blurX_set = 3;
const int flash_filters_BlurFilter_blurY_get = 4;
const int flash_filters_BlurFilter_blurY_set = 5;
const int flash_filters_BlurFilter_quality_get = 6;
const int flash_filters_BlurFilter_quality_set = 7;
const int flash_filters_BlurFilter_clone = 8;
const int abcclass_flash_filters_BlurFilter = 0;
extern const int BlurFilter_abc_length;
extern const int BlurFilter_abc_method_count;
extern const int BlurFilter_abc_class_count;
extern const int BlurFilter_abc_script_count;
extern const unsigned char BlurFilter_abc_data[];
