const int flash_filters_DisplacementMapFilter_DisplacementMapFilter = 1;
const int flash_filters_DisplacementMapFilter_mapBitmap_get = 2;
const int flash_filters_DisplacementMapFilter_mapBitmap_set = 3;
const int flash_filters_DisplacementMapFilter_mapPoint_get = 4;
const int flash_filters_DisplacementMapFilter_mapPoint_set = 5;
const int flash_filters_DisplacementMapFilter_componentX_get = 6;
const int flash_filters_DisplacementMapFilter_componentX_set = 7;
const int flash_filters_DisplacementMapFilter_componentY_get = 8;
const int flash_filters_DisplacementMapFilter_componentY_set = 9;
const int flash_filters_DisplacementMapFilter_scaleX_get = 10;
const int flash_filters_DisplacementMapFilter_scaleX_set = 11;
const int flash_filters_DisplacementMapFilter_scaleY_get = 12;
const int flash_filters_DisplacementMapFilter_scaleY_set = 13;
const int flash_filters_DisplacementMapFilter_mode_get = 14;
const int flash_filters_DisplacementMapFilter_mode_set = 15;
const int flash_filters_DisplacementMapFilter_color_get = 16;
const int flash_filters_DisplacementMapFilter_color_set = 17;
const int flash_filters_DisplacementMapFilter_alpha_get = 18;
const int flash_filters_DisplacementMapFilter_alpha_set = 19;
const int flash_filters_DisplacementMapFilter_clone = 20;
const int abcclass_flash_filters_DisplacementMapFilter = 0;
extern const int DisplacementMapFilter_abc_length;
extern const int DisplacementMapFilter_abc_method_count;
extern const int DisplacementMapFilter_abc_class_count;
extern const int DisplacementMapFilter_abc_script_count;
extern const unsigned char DisplacementMapFilter_abc_data[];
