const int flash_filters_DropShadowFilter_DropShadowFilter = 1;
const int flash_filters_DropShadowFilter_distance_get = 2;
const int flash_filters_DropShadowFilter_distance_set = 3;
const int flash_filters_DropShadowFilter_angle_get = 4;
const int flash_filters_DropShadowFilter_angle_set = 5;
const int flash_filters_DropShadowFilter_color_get = 6;
const int flash_filters_DropShadowFilter_color_set = 7;
const int flash_filters_DropShadowFilter_alpha_get = 8;
const int flash_filters_DropShadowFilter_alpha_set = 9;
const int flash_filters_DropShadowFilter_blurX_get = 10;
const int flash_filters_DropShadowFilter_blurX_set = 11;
const int flash_filters_DropShadowFilter_blurY_get = 12;
const int flash_filters_DropShadowFilter_blurY_set = 13;
const int flash_filters_DropShadowFilter_hideObject_get = 14;
const int flash_filters_DropShadowFilter_hideObject_set = 15;
const int flash_filters_DropShadowFilter_inner_get = 16;
const int flash_filters_DropShadowFilter_inner_set = 17;
const int flash_filters_DropShadowFilter_knockout_get = 18;
const int flash_filters_DropShadowFilter_knockout_set = 19;
const int flash_filters_DropShadowFilter_quality_get = 20;
const int flash_filters_DropShadowFilter_quality_set = 21;
const int flash_filters_DropShadowFilter_strength_get = 22;
const int flash_filters_DropShadowFilter_strength_set = 23;
const int flash_filters_DropShadowFilter_clone = 24;
const int abcclass_flash_filters_DropShadowFilter = 0;
extern const int DropShadowFilter_abc_length;
extern const int DropShadowFilter_abc_method_count;
extern const int DropShadowFilter_abc_class_count;
extern const int DropShadowFilter_abc_script_count;
extern const unsigned char DropShadowFilter_abc_data[];
