const int flash_filters_GlowFilter_GlowFilter = 1;
const int flash_filters_GlowFilter_color_get = 2;
const int flash_filters_GlowFilter_color_set = 3;
const int flash_filters_GlowFilter_alpha_get = 4;
const int flash_filters_GlowFilter_alpha_set = 5;
const int flash_filters_GlowFilter_blurX_get = 6;
const int flash_filters_GlowFilter_blurX_set = 7;
const int flash_filters_GlowFilter_blurY_get = 8;
const int flash_filters_GlowFilter_blurY_set = 9;
const int flash_filters_GlowFilter_inner_get = 10;
const int flash_filters_GlowFilter_inner_set = 11;
const int flash_filters_GlowFilter_knockout_get = 12;
const int flash_filters_GlowFilter_knockout_set = 13;
const int flash_filters_GlowFilter_quality_get = 14;
const int flash_filters_GlowFilter_quality_set = 15;
const int flash_filters_GlowFilter_strength_get = 16;
const int flash_filters_GlowFilter_strength_set = 17;
const int flash_filters_GlowFilter_clone = 18;
const int abcclass_flash_filters_GlowFilter = 0;
extern const int GlowFilter_abc_length;
extern const int GlowFilter_abc_method_count;
extern const int GlowFilter_abc_class_count;
extern const int GlowFilter_abc_script_count;
extern const unsigned char GlowFilter_abc_data[];
