const int flash_filters_GradientGlowFilter_GradientGlowFilter = 1;
const int flash_filters_GradientGlowFilter_angle_get = 2;
const int flash_filters_GradientGlowFilter_angle_set = 3;
const int flash_filters_GradientGlowFilter_alphas_get = 4;
const int flash_filters_GradientGlowFilter_alphas_set = 5;
const int flash_filters_GradientGlowFilter_blurX_get = 6;
const int flash_filters_GradientGlowFilter_blurX_set = 7;
const int flash_filters_GradientGlowFilter_blurY_get = 8;
const int flash_filters_GradientGlowFilter_blurY_set = 9;
const int flash_filters_GradientGlowFilter_colors_get = 10;
const int flash_filters_GradientGlowFilter_colors_set = 11;
const int flash_filters_GradientGlowFilter_distance_get = 12;
const int flash_filters_GradientGlowFilter_distance_set = 13;
const int flash_filters_GradientGlowFilter_knockout_get = 14;
const int flash_filters_GradientGlowFilter_knockout_set = 15;
const int flash_filters_GradientGlowFilter_quality_get = 16;
const int flash_filters_GradientGlowFilter_quality_set = 17;
const int flash_filters_GradientGlowFilter_ratios_get = 18;
const int flash_filters_GradientGlowFilter_ratios_set = 19;
const int flash_filters_GradientGlowFilter_strength_get = 20;
const int flash_filters_GradientGlowFilter_strength_set = 21;
const int flash_filters_GradientGlowFilter_type_get = 22;
const int flash_filters_GradientGlowFilter_type_set = 23;
const int flash_filters_GradientGlowFilter_clone = 24;
const int abcclass_flash_filters_GradientGlowFilter = 0;
extern const int GradientGlowFilter_abc_length;
extern const int GradientGlowFilter_abc_method_count;
extern const int GradientGlowFilter_abc_class_count;
extern const int GradientGlowFilter_abc_script_count;
extern const unsigned char GradientGlowFilter_abc_data[];
