const int flash_filters_GradientBevelFilter_GradientBevelFilter = 1;
const int flash_filters_GradientBevelFilter_distance_get = 2;
const int flash_filters_GradientBevelFilter_distance_set = 3;
const int flash_filters_GradientBevelFilter_angle_get = 4;
const int flash_filters_GradientBevelFilter_angle_set = 5;
const int flash_filters_GradientBevelFilter_colors_get = 6;
const int flash_filters_GradientBevelFilter_colors_set = 7;
const int flash_filters_GradientBevelFilter_alphas_get = 8;
const int flash_filters_GradientBevelFilter_alphas_set = 9;
const int flash_filters_GradientBevelFilter_ratios_get = 10;
const int flash_filters_GradientBevelFilter_ratios_set = 11;
const int flash_filters_GradientBevelFilter_blurX_get = 12;
const int flash_filters_GradientBevelFilter_blurX_set = 13;
const int flash_filters_GradientBevelFilter_blurY_get = 14;
const int flash_filters_GradientBevelFilter_blurY_set = 15;
const int flash_filters_GradientBevelFilter_knockout_get = 16;
const int flash_filters_GradientBevelFilter_knockout_set = 17;
const int flash_filters_GradientBevelFilter_quality_get = 18;
const int flash_filters_GradientBevelFilter_quality_set = 19;
const int flash_filters_GradientBevelFilter_strength_get = 20;
const int flash_filters_GradientBevelFilter_strength_set = 21;
const int flash_filters_GradientBevelFilter_type_get = 22;
const int flash_filters_GradientBevelFilter_type_set = 23;
const int flash_filters_GradientBevelFilter_clone = 24;
const int abcclass_flash_filters_GradientBevelFilter = 0;
extern const int GradientBevelFilter_abc_length;
extern const int GradientBevelFilter_abc_method_count;
extern const int GradientBevelFilter_abc_class_count;
extern const int GradientBevelFilter_abc_script_count;
extern const unsigned char GradientBevelFilter_abc_data[];
