const int flash_system_ApplicationDomain_currentDomain_get = 1;
const int flash_system_ApplicationDomain_MIN_DOMAIN_MEMORY_LENGTH_get = 2;
const int flash_system_ApplicationDomain_ApplicationDomain = 3;
const int flash_system_ApplicationDomain_parentDomain_get = 4;
const int flash_system_ApplicationDomain_domainMemory_get = 5;
const int flash_system_ApplicationDomain_domainMemory_set = 6;
const int flash_system_ApplicationDomain_getDefinition = 7;
const int flash_system_ApplicationDomain_hasDefinition = 8;
const int flash_system_ApplicationDomain_getQualifiedDefinitionNames = 9;
const int abcclass_flash_system_ApplicationDomain = 0;
extern const int ApplicationDomain_abc_length;
extern const int ApplicationDomain_abc_method_count;
extern const int ApplicationDomain_abc_class_count;
extern const int ApplicationDomain_abc_script_count;
extern const unsigned char ApplicationDomain_abc_data[];
