const int flash_system_Capabilities_isEmbeddedInAcrobat_get = 1;
const int flash_system_Capabilities_hasEmbeddedVideo_get = 2;
const int flash_system_Capabilities_hasAudio_get = 3;
const int flash_system_Capabilities_avHardwareDisable_get = 4;
const int flash_system_Capabilities_hasAccessibility_get = 5;
const int flash_system_Capabilities_hasAudioEncoder_get = 6;
const int flash_system_Capabilities_hasMP3_get = 7;
const int flash_system_Capabilities_hasPrinting_get = 8;
const int flash_system_Capabilities_hasScreenBroadcast_get = 9;
const int flash_system_Capabilities_hasScreenPlayback_get = 10;
const int flash_system_Capabilities_hasStreamingAudio_get = 11;
const int flash_system_Capabilities_hasStreamingVideo_get = 12;
const int flash_system_Capabilities_hasVideoEncoder_get = 13;
const int flash_system_Capabilities_isDebugger_get = 14;
const int flash_system_Capabilities_localFileReadDisable_get = 15;
const int flash_system_Capabilities_language_get = 16;
const int flash_system_Capabilities_manufacturer_get = 17;
const int flash_system_Capabilities_os_get = 18;
const int flash_system_Capabilities_cpuArchitecture_get = 19;
const int flash_system_Capabilities_playerType_get = 20;
const int flash_system_Capabilities_serverString_get = 21;
const int flash_system_Capabilities_version_get = 22;
const int flash_system_Capabilities_screenColor_get = 23;
const int flash_system_Capabilities_pixelAspectRatio_get = 24;
const int flash_system_Capabilities_screenDPI_get = 25;
const int flash_system_Capabilities_screenResolutionX_get = 26;
const int flash_system_Capabilities_screenResolutionY_get = 27;
const int flash_system_Capabilities_touchscreenType_get = 28;
const int flash_system_Capabilities_hasIME_get = 29;
const int flash_system_Capabilities_hasTLS_get = 30;
const int flash_system_Capabilities_maxLevelIDC_get = 31;
const int flash_system_Capabilities_supports32BitProcesses_get = 32;
const int flash_system_Capabilities_supports64BitProcesses_get = 33;
const int flash_system_Capabilities__internal_get = 34;
const int flash_system_Capabilities_hasMultiChannelAudio = 35;
const int abcclass_flash_system_Capabilities = 0;
extern const int Capabilities_abc_length;
extern const int Capabilities_abc_method_count;
extern const int Capabilities_abc_class_count;
extern const int Capabilities_abc_script_count;
extern const unsigned char Capabilities_abc_data[];
