const int flash_system_Security_exactSettings_get = 1;
const int flash_system_Security_exactSettings_set = 2;
const int flash_system_Security_disableAVM1Loading_get = 3;
const int flash_system_Security_disableAVM1Loading_set = 4;
const int flash_system_Security_sandboxType_get = 5;
const int flash_system_Security_pageDomain_get = 6;
const int flash_system_Security_allowDomain = 7;
const int flash_system_Security_allowInsecureDomain = 8;
const int flash_system_Security_loadPolicyFile = 9;
const int flash_system_Security_showSettings = 10;
const int flash_system_Security_flash_system_duplicateSandboxBridgeInputArguments = 11;
const int flash_system_Security_flash_system_duplicateSandboxBridgeOutputArgument = 12;
const int abcclass_flash_system_Security = 0;
extern const int Security_abc_length;
extern const int Security_abc_method_count;
extern const int Security_abc_class_count;
extern const int Security_abc_script_count;
extern const unsigned char Security_abc_data[];
