const int flash_security_X509Certificate_version_get = 2;
const int flash_security_X509Certificate_serialNumber_get = 3;
const int flash_security_X509Certificate_signatureAlgorithmOID_get = 4;
const int flash_security_X509Certificate_signatureAlgorithmParams_get = 5;
const int flash_security_X509Certificate_issuer_get = 6;
const int flash_security_X509Certificate_validNotBefore_get = 7;
const int flash_security_X509Certificate_validNotAfter_get = 8;
const int flash_security_X509Certificate_subject_get = 9;
const int flash_security_X509Certificate_subjectPublicKeyAlgorithmOID_get = 10;
const int flash_security_X509Certificate_subjectPublicKey_get = 11;
const int flash_security_X509Certificate_issuerUniqueID_get = 12;
const int flash_security_X509Certificate_subjectUniqueID_get = 13;
const int flash_security_X509Certificate_encoded_get = 14;
const int abcclass_flash_security_X509Certificate = 0;
extern const int X509Certificate_abc_length;
extern const int X509Certificate_abc_method_count;
extern const int X509Certificate_abc_class_count;
extern const int X509Certificate_abc_script_count;
extern const unsigned char X509Certificate_abc_data[];
