const int flash_geom_Transform_Transform = 1;
const int flash_geom_Transform_matrix_get = 2;
const int flash_geom_Transform_matrix_set = 3;
const int flash_geom_Transform_colorTransform_get = 4;
const int flash_geom_Transform_colorTransform_set = 5;
const int flash_geom_Transform_concatenatedMatrix_get = 6;
const int flash_geom_Transform_concatenatedColorTransform_get = 7;
const int flash_geom_Transform_pixelBounds_get = 8;
const int flash_geom_Transform_matrix3D_get = 9;
const int flash_geom_Transform_matrix3D_set = 10;
const int flash_geom_Transform_getRelativeMatrix3D = 11;
const int flash_geom_Transform_perspectiveProjection_get = 12;
const int flash_geom_Transform_perspectiveProjection_set = 13;
const int abcclass_flash_geom_Transform = 0;
extern const int Transform_abc_length;
extern const int Transform_abc_method_count;
extern const int Transform_abc_class_count;
extern const int Transform_abc_script_count;
extern const unsigned char Transform_abc_data[];
