const int flash_geom_ColorTransform_redMultiplier_set = 1;
const int flash_geom_ColorTransform_redMultiplier_get = 2;
const int flash_geom_ColorTransform_greenMultiplier_set = 3;
const int flash_geom_ColorTransform_greenMultiplier_get = 4;
const int flash_geom_ColorTransform_blueMultiplier_set = 5;
const int flash_geom_ColorTransform_blueMultiplier_get = 6;
const int flash_geom_ColorTransform_alphaMultiplier_set = 7;
const int flash_geom_ColorTransform_alphaMultiplier_get = 8;
const int flash_geom_ColorTransform_redOffset_set = 9;
const int flash_geom_ColorTransform_redOffset_get = 10;
const int flash_geom_ColorTransform_greenOffset_set = 11;
const int flash_geom_ColorTransform_greenOffset_get = 12;
const int flash_geom_ColorTransform_blueOffset_set = 13;
const int flash_geom_ColorTransform_blueOffset_get = 14;
const int flash_geom_ColorTransform_alphaOffset_set = 15;
const int flash_geom_ColorTransform_alphaOffset_get = 16;
const int flash_geom_ColorTransform_ColorTransform = 17;
const int flash_geom_ColorTransform_color_get = 18;
const int flash_geom_ColorTransform_color_set = 19;
const int flash_geom_ColorTransform_concat = 20;
const int flash_geom_ColorTransform_toString = 21;
const int abcclass_flash_geom_ColorTransform = 0;
extern const int ColorTransform_abc_length;
extern const int ColorTransform_abc_method_count;
extern const int ColorTransform_abc_class_count;
extern const int ColorTransform_abc_script_count;
extern const unsigned char ColorTransform_abc_data[];
