const int flash_geom_Matrix_a_set = 1;
const int flash_geom_Matrix_a_get = 2;
const int flash_geom_Matrix_b_set = 3;
const int flash_geom_Matrix_b_get = 4;
const int flash_geom_Matrix_c_set = 5;
const int flash_geom_Matrix_c_get = 6;
const int flash_geom_Matrix_d_set = 7;
const int flash_geom_Matrix_d_get = 8;
const int flash_geom_Matrix_tx_set = 9;
const int flash_geom_Matrix_tx_get = 10;
const int flash_geom_Matrix_ty_set = 11;
const int flash_geom_Matrix_ty_get = 12;
const int flash_geom_Matrix_Matrix = 13;
const int flash_geom_Matrix_concat = 14;
const int flash_geom_Matrix_invert = 15;
const int flash_geom_Matrix_identity = 16;
const int flash_geom_Matrix_createBox = 17;
const int flash_geom_Matrix_createGradientBox = 18;
const int flash_geom_Matrix_rotate = 19;
const int flash_geom_Matrix_translate = 20;
const int flash_geom_Matrix_scale = 21;
const int flash_geom_Matrix_deltaTransformPoint = 22;
const int flash_geom_Matrix_transformPoint = 23;
const int flash_geom_Matrix_copyFrom = 24;
const int flash_geom_Matrix_setTo = 25;
const int flash_geom_Matrix_copyRowTo = 26;
const int flash_geom_Matrix_copyColumnTo = 27;
const int flash_geom_Matrix_copyRowFrom = 28;
const int flash_geom_Matrix_copyColumnFrom = 29;
const int flash_geom_Matrix_clone = 30;
const int flash_geom_Matrix_toString = 31;
const int abcclass_flash_geom_Matrix = 0;
extern const int Matrix_abc_length;
extern const int Matrix_abc_method_count;
extern const int Matrix_abc_class_count;
extern const int Matrix_abc_script_count;
extern const unsigned char Matrix_abc_data[];
