const int flash_geom_Matrix3D_interpolate = 1;
const int flash_geom_Matrix3D_Matrix3D = 2;
const int flash_geom_Matrix3D_rawData_get = 3;
const int flash_geom_Matrix3D_rawData_set = 4;
const int flash_geom_Matrix3D_position_get = 5;
const int flash_geom_Matrix3D_position_set = 6;
const int flash_geom_Matrix3D_determinant_get = 7;
const int flash_geom_Matrix3D_clone = 8;
const int flash_geom_Matrix3D_copyToMatrix3D = 9;
const int flash_geom_Matrix3D_append = 10;
const int flash_geom_Matrix3D_prepend = 11;
const int flash_geom_Matrix3D_invert = 12;
const int flash_geom_Matrix3D_identity = 13;
const int flash_geom_Matrix3D_decompose = 14;
const int flash_geom_Matrix3D_recompose = 15;
const int flash_geom_Matrix3D_appendTranslation = 16;
const int flash_geom_Matrix3D_appendRotation = 17;
const int flash_geom_Matrix3D_appendScale = 18;
const int flash_geom_Matrix3D_prependTranslation = 19;
const int flash_geom_Matrix3D_prependRotation = 20;
const int flash_geom_Matrix3D_prependScale = 21;
const int flash_geom_Matrix3D_transformVector = 22;
const int flash_geom_Matrix3D_deltaTransformVector = 23;
const int flash_geom_Matrix3D_transformVectors = 24;
const int flash_geom_Matrix3D_transpose = 25;
const int flash_geom_Matrix3D_pointAt = 26;
const int flash_geom_Matrix3D_interpolateTo = 27;
const int flash_geom_Matrix3D_copyFrom = 28;
const int flash_geom_Matrix3D_copyRawDataTo = 29;
const int flash_geom_Matrix3D_copyRawDataFrom = 30;
const int flash_geom_Matrix3D_copyRowTo = 31;
const int flash_geom_Matrix3D_copyColumnTo = 32;
const int flash_geom_Matrix3D_copyRowFrom = 33;
const int flash_geom_Matrix3D_copyColumnFrom = 34;
const int abcclass_flash_geom_Matrix3D = 0;
extern const int Matrix3D_abc_length;
extern const int Matrix3D_abc_method_count;
extern const int Matrix3D_abc_class_count;
extern const int Matrix3D_abc_script_count;
extern const unsigned char Matrix3D_abc_data[];
