const int flash_geom_Point_interpolate = 1;
const int flash_geom_Point_distance = 2;
const int flash_geom_Point_polar = 3;
const int flash_geom_Point_x_set = 4;
const int flash_geom_Point_x_get = 5;
const int flash_geom_Point_y_set = 6;
const int flash_geom_Point_y_get = 7;
const int flash_geom_Point_Point = 8;
const int flash_geom_Point_length_get = 9;
const int flash_geom_Point_clone = 10;
const int flash_geom_Point_offset = 11;
const int flash_geom_Point_equals = 12;
const int flash_geom_Point_subtract = 13;
const int flash_geom_Point_add = 14;
const int flash_geom_Point_normalize = 15;
const int flash_geom_Point_copyFrom = 16;
const int flash_geom_Point_setTo = 17;
const int flash_geom_Point_toString = 18;
const int abcclass_flash_geom_Point = 0;
extern const int Point_abc_length;
extern const int Point_abc_method_count;
extern const int Point_abc_class_count;
extern const int Point_abc_script_count;
extern const unsigned char Point_abc_data[];
