const int flash_geom_Rectangle_x_set = 1;
const int flash_geom_Rectangle_x_get = 2;
const int flash_geom_Rectangle_y_set = 3;
const int flash_geom_Rectangle_y_get = 4;
const int flash_geom_Rectangle_width_set = 5;
const int flash_geom_Rectangle_width_get = 6;
const int flash_geom_Rectangle_height_set = 7;
const int flash_geom_Rectangle_height_get = 8;
const int flash_geom_Rectangle_Rectangle = 9;
const int flash_geom_Rectangle_left_get = 10;
const int flash_geom_Rectangle_left_set = 11;
const int flash_geom_Rectangle_right_get = 12;
const int flash_geom_Rectangle_right_set = 13;
const int flash_geom_Rectangle_top_get = 14;
const int flash_geom_Rectangle_top_set = 15;
const int flash_geom_Rectangle_bottom_get = 16;
const int flash_geom_Rectangle_bottom_set = 17;
const int flash_geom_Rectangle_topLeft_get = 18;
const int flash_geom_Rectangle_topLeft_set = 19;
const int flash_geom_Rectangle_bottomRight_get = 20;
const int flash_geom_Rectangle_bottomRight_set = 21;
const int flash_geom_Rectangle_size_get = 22;
const int flash_geom_Rectangle_size_set = 23;
const int flash_geom_Rectangle_clone = 24;
const int flash_geom_Rectangle_isEmpty = 25;
const int flash_geom_Rectangle_setEmpty = 26;
const int flash_geom_Rectangle_inflate = 27;
const int flash_geom_Rectangle_inflatePoint = 28;
const int flash_geom_Rectangle_offset = 29;
const int flash_geom_Rectangle_offsetPoint = 30;
const int flash_geom_Rectangle_contains = 31;
const int flash_geom_Rectangle_containsPoint = 32;
const int flash_geom_Rectangle_containsRect = 33;
const int flash_geom_Rectangle_intersection = 34;
const int flash_geom_Rectangle_intersects = 35;
const int flash_geom_Rectangle_union = 36;
const int flash_geom_Rectangle_equals = 37;
const int flash_geom_Rectangle_copyFrom = 38;
const int flash_geom_Rectangle_setTo = 39;
const int flash_geom_Rectangle_toString = 40;
const int abcclass_flash_geom_Rectangle = 0;
extern const int Rectangle_abc_length;
extern const int Rectangle_abc_method_count;
extern const int Rectangle_abc_class_count;
extern const int Rectangle_abc_script_count;
extern const unsigned char Rectangle_abc_data[];
