const int flash_geom_Vector3D_angleBetween = 1;
const int flash_geom_Vector3D_distance = 2;
const int flash_geom_Vector3D_x_get = 3;
const int flash_geom_Vector3D_x_set = 4;
const int flash_geom_Vector3D_y_get = 5;
const int flash_geom_Vector3D_y_set = 6;
const int flash_geom_Vector3D_z_get = 7;
const int flash_geom_Vector3D_z_set = 8;
const int flash_geom_Vector3D_w_get = 9;
const int flash_geom_Vector3D_w_set = 10;
const int flash_geom_Vector3D_Vector3D = 11;
const int flash_geom_Vector3D_length_get = 12;
const int flash_geom_Vector3D_lengthSquared_get = 13;
const int flash_geom_Vector3D_dotProduct = 14;
const int flash_geom_Vector3D_crossProduct = 15;
const int flash_geom_Vector3D_normalize = 16;
const int flash_geom_Vector3D_scaleBy = 17;
const int flash_geom_Vector3D_incrementBy = 18;
const int flash_geom_Vector3D_decrementBy = 19;
const int flash_geom_Vector3D_add = 20;
const int flash_geom_Vector3D_subtract = 21;
const int flash_geom_Vector3D_negate = 22;
const int flash_geom_Vector3D_equals = 23;
const int flash_geom_Vector3D_nearEquals = 24;
const int flash_geom_Vector3D_project = 25;
const int flash_geom_Vector3D_copyFrom = 26;
const int flash_geom_Vector3D_setTo = 27;
const int flash_geom_Vector3D_clone = 28;
const int flash_geom_Vector3D_toString = 29;
const int abcclass_flash_geom_Vector3D = 0;
extern const int Vector3D_abc_length;
extern const int Vector3D_abc_method_count;
extern const int Vector3D_abc_class_count;
extern const int Vector3D_abc_script_count;
extern const unsigned char Vector3D_abc_data[];
