const int flash_globalization_Collator_getAvailableLocaleIDNames = 1;
const int flash_globalization_Collator_ignoreCase_get = 3;
const int flash_globalization_Collator_ignoreCase_set = 4;
const int flash_globalization_Collator_ignoreDiacritics_get = 5;
const int flash_globalization_Collator_ignoreDiacritics_set = 6;
const int flash_globalization_Collator_ignoreKanaType_get = 7;
const int flash_globalization_Collator_ignoreKanaType_set = 8;
const int flash_globalization_Collator_ignoreSymbols_get = 9;
const int flash_globalization_Collator_ignoreSymbols_set = 10;
const int flash_globalization_Collator_ignoreCharacterWidth_get = 11;
const int flash_globalization_Collator_ignoreCharacterWidth_set = 12;
const int flash_globalization_Collator_numericComparison_get = 13;
const int flash_globalization_Collator_numericComparison_set = 14;
const int flash_globalization_Collator_lastOperationStatus_get = 15;
const int flash_globalization_Collator_actualLocaleIDName_get = 16;
const int flash_globalization_Collator_requestedLocaleIDName_get = 17;
const int flash_globalization_Collator_compare = 18;
const int flash_globalization_Collator_equals = 19;
const int flash_globalization_Collator_private_ctor = 20;
const int abcclass_flash_globalization_Collator = 0;
extern const int Collator_abc_length;
extern const int Collator_abc_method_count;
extern const int Collator_abc_class_count;
extern const int Collator_abc_script_count;
extern const unsigned char Collator_abc_data[];
