const int flash_filters_ColorMatrixFilter_ColorMatrixFilter = 1;
const int flash_filters_ColorMatrixFilter_matrix_get = 2;
const int flash_filters_ColorMatrixFilter_matrix_set = 3;
const int flash_filters_ColorMatrixFilter_clone = 4;
const int abcclass_flash_filters_ColorMatrixFilter = 0;
extern const int ColorMatrixFilter_abc_length;
extern const int ColorMatrixFilter_abc_method_count;
extern const int ColorMatrixFilter_abc_class_count;
extern const int ColorMatrixFilter_abc_script_count;
extern const unsigned char ColorMatrixFilter_abc_data[];
