const int flash_filters_ConvolutionFilter_ConvolutionFilter = 1;
const int flash_filters_ConvolutionFilter_matrix_get = 2;
const int flash_filters_ConvolutionFilter_matrix_set = 3;
const int flash_filters_ConvolutionFilter_matrixX_get = 4;
const int flash_filters_ConvolutionFilter_matrixX_set = 5;
const int flash_filters_ConvolutionFilter_matrixY_get = 6;
const int flash_filters_ConvolutionFilter_matrixY_set = 7;
const int flash_filters_ConvolutionFilter_divisor_get = 8;
const int flash_filters_ConvolutionFilter_divisor_set = 9;
const int flash_filters_ConvolutionFilter_bias_get = 10;
const int flash_filters_ConvolutionFilter_bias_set = 11;
const int flash_filters_ConvolutionFilter_preserveAlpha_get = 12;
const int flash_filters_ConvolutionFilter_preserveAlpha_set = 13;
const int flash_filters_ConvolutionFilter_clamp_get = 14;
const int flash_filters_ConvolutionFilter_clamp_set = 15;
const int flash_filters_ConvolutionFilter_color_get = 16;
const int flash_filters_ConvolutionFilter_color_set = 17;
const int flash_filters_ConvolutionFilter_alpha_get = 18;
const int flash_filters_ConvolutionFilter_alpha_set = 19;
const int flash_filters_ConvolutionFilter_clone = 20;
const int abcclass_flash_filters_ConvolutionFilter = 0;
extern const int ConvolutionFilter_abc_length;
extern const int ConvolutionFilter_abc_method_count;
extern const int ConvolutionFilter_abc_class_count;
extern const int ConvolutionFilter_abc_script_count;
extern const unsigned char ConvolutionFilter_abc_data[];
