const int flash_media_SoundChannel_position_get = 2;
const int flash_media_SoundChannel_soundTransform_get = 3;
const int flash_media_SoundChannel_soundTransform_set = 4;
const int flash_media_SoundChannel_leftPeak_get = 5;
const int flash_media_SoundChannel_rightPeak_get = 6;
const int flash_media_SoundChannel_stop = 7;
const int abcclass_flash_media_SoundChannel = 0;
extern const int SoundChannel_abc_length;
extern const int SoundChannel_abc_method_count;
extern const int SoundChannel_abc_class_count;
extern const int SoundChannel_abc_script_count;
extern const unsigned char SoundChannel_abc_data[];
