const int flash_media_Sound_Sound = 1;
const int flash_media_Sound_url_get = 2;
const int flash_media_Sound_isURLInaccessible_get = 3;
const int flash_media_Sound_length_get = 4;
const int flash_media_Sound_isBuffering_get = 5;
const int flash_media_Sound_bytesLoaded_get = 6;
const int flash_media_Sound_bytesTotal_get = 7;
const int flash_media_Sound_id3_get = 8;
const int flash_media_Sound_load = 9;
const int flash_media_Sound_loadCompressedDataFromByteArray = 10;
const int flash_media_Sound_loadPCMFromByteArray = 11;
const int flash_media_Sound_play = 12;
const int flash_media_Sound_close = 13;
const int flash_media_Sound_extract = 14;
const int abcclass_flash_media_Sound = 0;
extern const int Sound_abc_length;
extern const int Sound_abc_method_count;
extern const int Sound_abc_class_count;
extern const int Sound_abc_script_count;
extern const unsigned char Sound_abc_data[];
